import React,{useEffect,useRef,useState} from 'react';
import {Modal,Pressable,ScrollView,Text,View} from 'react-native';
import {useAccount} from '../commerce/account-context';
import {getLevel} from '../game/level';
import rules from '../../shared/rules-manifest.json';
import type {DailyManifest,Leaderboard,RunTicket} from '../../shared/ranked';
import {rankedApi} from './api';
import {readPending,clearPending,type PendingRun} from './pending';
export default function DailyPanel({visible,onClose,onStart}:{visible:boolean;onClose:()=>void;onStart:(ticket:RunTicket)=>void}){
 const identity=useAccount(),[daily,setDaily]=useState<DailyManifest>(),[board,setBoard]=useState<Leaderboard>(),[current,setCurrent]=useState<RunTicket|null>(null),[pending,setPending]=useState<PendingRun|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const generation=useRef(0),busyRef=useRef(false),identityRef=useRef(identity);identityRef.current=identity;
 useEffect(()=>{generation.current++;if(!visible)return;const g=generation.current;setMessage('');setDaily(undefined);setBoard(undefined);setCurrent(null);setPending(null);
  void(async()=>{try{const manifest=await rankedApi.daily(),scores=await rankedApi.leaderboard(manifest.day);if(g!==generation.current)return;setDaily(manifest);setBoard(scores);
   if(identity.wallet&&!identity.preview){const saved=await readPending(identity.wallet);if(g!==generation.current)return;setPending(saved);try{const s=await identity.session(false),active=await rankedApi.current(s.token),personal=await rankedApi.leaderboard(manifest.day,s.token);if(g===generation.current){setCurrent(active);setBoard(personal);}}catch{/* Browsing does not open a wallet sign-in. */}}
  }catch(e){if(g===generation.current)setMessage(e instanceof Error?e.message:'Daily challenge unavailable.');}})();return()=>{generation.current++;};
 },[visible,identity.wallet]);
 type Active=()=>boolean;
 async function act(fn:(active:Active)=>Promise<void>){if(busyRef.current)return;const g=generation.current;const active=()=>g===generation.current;busyRef.current=true;setBusy(true);setMessage('');try{await fn(active);}catch(e){if(active())setMessage(e instanceof Error?e.message:'Could not complete this request.');}finally{busyRef.current=false;setBusy(false);}}
 async function refresh(active:Active){const manifest=await rankedApi.daily();if(!active())return;if(identity.preview){const scores=await rankedApi.leaderboard(manifest.day);if(active()){setDaily(manifest);setBoard(scores);}return;}const s=await identity.session();if(!active())return;const [run,saved,scores]=await Promise.all([rankedApi.current(s.token),readPending(s.wallet),rankedApi.leaderboard(manifest.day,s.token)]);if(active()){setDaily(manifest);setCurrent(run);setPending(saved);setBoard(scores);}}
 async function start(active:Active){if(!daily)return;if(identity.preview)throw new Error('Use the Android app and a connected wallet to enter a verified daily run.');if(daily.rulesHash!==rules.rulesHash||daily.levelHash!==rules.levelHashes[daily.mission as keyof typeof rules.levelHashes])throw new Error('Update the app to play today’s rules.');
  const s=await identity.session();if(s.wallet!==identityRef.current.wallet)throw new Error('Wallet changed. Refresh the daily challenge.');
  if(!active())return;const saved=await readPending(s.wallet);if(!active())return;if(saved)throw new Error('Submit or clear the saved result before starting a new daily run.');
  const ticket=await rankedApi.start(s.token,daily,crypto.randomUUID());if(!active())return;if(s.wallet!==identityRef.current.wallet)throw new Error('Wallet changed. The ticket remains available to its original wallet.');if(ticket.status!=='issued'||new Date(ticket.expiresAt).getTime()<=Date.now())throw new Error('This ticket is no longer playable. Refresh the challenge.');onStart(ticket);
 }
 async function retrySaved(active:Active){const s=await identity.session();if(!active())return;const saved=await readPending(s.wallet);if(!active())return;if(!saved)throw new Error('No saved daily result.');let result=await rankedApi.run(s.token,saved.id);if(!active())return;if(result.status==='issued')result=await rankedApi.finish(s.token,saved.id,saved.rulesHash,saved.replay);if(!['issued','verifying'].includes(result.status))await clearPending(s.wallet,saved.id);if(!active())return;setCurrent(result);setMessage(result.detail??result.status);if(!['issued','verifying'].includes(result.status))setPending(null);if(daily){const scores=await rankedApi.leaderboard(daily.day,s.token);if(active())setBoard(scores);}}
 async function abandon(active:Active){const s=await identity.session();if(!active())return;const run=current??(pending?await rankedApi.run(s.token,pending.id):null);if(!active()||!run)return;if(run.status==='verifying')throw new Error('Verification is already queued. Refresh to check the result.');if(run.status==='issued')await rankedApi.abandon(s.token,run.id);await clearPending(s.wallet,run.id);if(!active())return;setPending(null);setCurrent(null);setMessage('Previous run closed. You can start a new daily attempt.');}
 const button=(text:string,fn:(active:Active)=>Promise<void>)=><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void act(fn)} style={{padding:14,borderRadius:11,backgroundColor:'#cfe6e4',opacity:busy?.5:1}}><Text style={{color:'#17392d',fontWeight:'700',textAlign:'center'}}>{text}</Text></Pressable>;
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={{flex:1,backgroundColor:'#081210ed',justifyContent:'center',padding:20}}><ScrollView style={{flexGrow:0,maxHeight:'92%',borderRadius:24,backgroundColor:'#142722'}} contentContainerStyle={{padding:22,gap:16}}>
  <Text style={{color:'#a8ecd7',fontSize:11,letterSpacing:2}}>DAILY CHALLENGE</Text><Text style={{color:'#e8f0e4',fontSize:30,fontWeight:'800'}}>{daily?getLevel(daily.mission).title:'One route. Your best run.'}</Text>
  {daily&&<><Text style={{color:'#b4cfc0',fontSize:13,lineHeight:21}}>{daily.day} · resets at 00:00 UTC · {getLevel(daily.mission).briefing}</Text><Text style={{color:'#b4cfc0',fontSize:13,lineHeight:21}}>Standard courier and mission tools for everyone. Free attempts with campaign access. Only server-verified extractions enter this leaderboard.</Text><Text style={{color:'#91b4a1',fontSize:12,lineHeight:19}}>Finish within {daily.hardLimitSeconds/60} minutes of game time. Your submission window keeps counting while paused or offline. No token rewards in this mode.</Text>{button(identity.preview?'Play on Android':'Start daily run',start)}</>}
  {current&&<Text style={{color:'#d2e6da',fontSize:13,lineHeight:21}}>Current attempt: {current.status} · {current.detail}</Text>}{pending&&button('Submit / check saved result',retrySaved)}{(current?.status==='issued'||(pending&&current?.status!=='verifying'))&&button('Abandon previous attempt / clear saved result',abandon)}
  {button(busy?'Loading…':'Refresh leaderboard',refresh)}
  {!!message&&<Text accessibilityLiveRegion="polite" style={{color:'#d1e8d8',fontSize:13,lineHeight:20}}>{message}</Text>}
  {board?.personal&&<View style={{padding:14,backgroundColor:'#294a3d',borderRadius:12}}><Text style={{color:'#d6ede0',fontWeight:'700'}}>Your rank: #{board.personal.rank} · {board.personal.score.toLocaleString()} points</Text></View>}
  <Text style={{color:'#e3ece2',fontSize:20,fontWeight:'700'}}>Top couriers</Text>{board?.entries.length?board.entries.map(row=><View key={row.wallet} style={{padding:12,borderWidth:row.frame?2:1,borderColor:row.frame?'#bee5d1':'#355349',borderRadius:10,gap:5}}><Text style={{color:'#d9eadf',fontSize:14}}>#{row.rank}  {row.wallet.slice(0,5)}…{row.wallet.slice(-5)}</Text><Text style={{color:'#a5c5b1',fontSize:12}}>{row.score.toLocaleString()} points · {row.seconds.toFixed(2)}s</Text></View>):<Text style={{color:'#91ae9b',fontSize:13}}>{board?'No verified extractions yet.':'Scores will appear when the service is available.'}</Text>}
  <Text style={{color:'#809e8c',fontSize:11,lineHeight:18}}>Scores are replay-verified, not proof of human play. Points rank first; a faster run breaks a tie.</Text><Pressable accessibilityRole="button" onPress={onClose} style={{padding:14}}><Text style={{color:'#bde8d2',textAlign:'center'}}>Close daily challenge</Text></Pressable>
 </ScrollView></View></Modal>;
}
