import React,{useRef,useState} from 'react';
import {Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View,useWindowDimensions} from 'react-native';
import {weekWindow,weeklyResetLabel} from '../../shared/weekly';
import {useDailyClock} from './useDailyClock';
import {NAV_ICONS} from '../components/BottomTabs';
import {useLeague} from '../league/useLeague';
import {type Contract} from '../../shared/contracts';
import type {RunTicket} from '../../shared/ranked';
import type {LeagueBoard,LeagueEntry} from '../../shared/league';
import MissionPreview from '../components/MissionPreview';
import CourierCard from '../league/CourierCard';
import {shareCard} from '../league/shareCard';
import {shortWallet,type CourierCardData} from '../league/card';
const arts=[require('../../assets/world-v3/district-warehouse.png'),require('../../assets/world-v3/district-rooftops.png'),require('../../assets/world-v3/district-powerworks.png')];
export function useWeekly(active=true){const now=useDailyClock(active),window=weekWindow(new Date(now));return {...useLeague(active,window.week),now,window};}
export function WeeklyCard({state,onPress}:{state:ReturnType<typeof useWeekly>;onPress:()=>void}){const p=state.data?.board.personal;return <Pressable accessibilityRole="button" accessibilityLabel="Open weekly leaderboard" onPress={onPress} testID="weekly-home-card" style={s.homeCard}><View style={s.medal}><Image source={NAV_ICONS.leaderboard} style={{width:24,height:24,tintColor:'#1B3835'}}/></View><View style={{flex:1,gap:3}}><Text style={s.kicker}>THREE CONTRACTS / THIS WEEK</Text><Text style={s.homeTitle}>{p?state.local?`${p.cleared}/3 test contracts cleared`:`Rank #${p.rank} · ${p.points.toLocaleString()} pts`:'Your next weekly climb'}</Text><Text style={s.muted}>{state.local?'Local test · ':''}{weeklyResetLabel(state.window.endsAt,state.now)}</Text></View><Text style={{color:'#CFE6E4',fontSize:24}}>›</Text></Pressable>;}
export default function WeeklyBoard({state,onStart,showStandings=false}:{showStandings?:boolean;state:ReturnType<typeof useWeekly>;onStart:(ticket:RunTicket)=>void}){
 const {data,local,busy,error,now}=state,{width,height}=useWindowDimensions(),[section,setSection]=useState<'contracts'|'standings'|'history'>(showStandings?'standings':'contracts'),[contract,setContract]=useState<Contract|null>(null),[confirm,setConfirm]=useState(false),[message,setMessage]=useState(''),[working,setWorking]=useState(false),[card,setCard]=useState<LeagueBoard|null>(null),[domain,setDomain]=useState(''),cardRef=useRef<View>(null),lock=useRef(false);
 async function act(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setWorking(true);setMessage('');try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'Please try again.');}finally{lock.current=false;setWorking(false);}}
 const button=(text:string,fn:()=>void,primary=false,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled||working} onPress={fn} style={[s.button,primary&&s.primary,(disabled||working)&&{opacity:.45}]}><Text style={[s.buttonText,primary&&{color:'#193B36'}]}>{text}</Text></Pressable>;
 const start=(c:Contract,practice:boolean)=>void act(async()=>{const ticket=await state.start(c,practice);onStart(ticket);});
 const personal=data?.board.personal;
 const row=(r:LeagueEntry,personal?:LeagueEntry|null)=><View key={r.wallet} style={[s.row,r.wallet===personal?.wallet&&s.yourRow]}><Text style={s.rankNumber}>{local?'•':r.rank}</Text><View style={{flex:1,gap:3}}><Text style={s.white}>{r.wallet===personal?.wallet?'You':shortWallet(r.wallet)}</Text><Text style={s.muted}>{r.cleared}/3 cleared · {(r.ticks/30).toFixed(2)}s</Text></View><Text style={s.white}>{r.points.toLocaleString()}</Text></View>;
 let cardData:CourierCardData|undefined;if(card)cardData={week:card.week,rank:card.personal?.rank??null,points:card.personal?.points??0,cleared:card.personal?.cleared??0,ticks:card.personal?.ticks??0,domain:data?.domain??null,wallet:card.personal?.wallet??'browser-playtest',final:card.final,local,earned:card.personal?.cleared===3};
 return <View style={{flex:1,minHeight:0,gap:8}} testID="weekly-leaderboard">
  {card&&cardData?<><View style={s.line}>{button('← Back',()=>setCard(null))}<Text style={s.white}>Your Courier Card</Text></View><ScrollView contentContainerStyle={{alignItems:'center',gap:10}}><CourierCard ref={cardRef} data={cardData} width={Math.min(width-52,(height-320)*.8,340)}/><Text style={[s.muted,{textAlign:'center'}]}>Share to Telegram, X or any compatible app. You choose where.</Text>{<View style={{width:'100%',gap:7}}><TextInput accessibilityLabel="Your .skr name" placeholder="yourname.skr" placeholderTextColor="#7B9590" autoCapitalize="none" value={domain} onChangeText={setDomain} style={s.input}/>{local&&<Text style={s.muted}>Name preview only. Android verifies wallet ownership.</Text>}{button(local?'Preview .skr name':'Verify my .skr',()=>void act(()=>state.identity(domain)))}</View>}</ScrollView><View style={{flexDirection:'row',gap:8,justifyContent:'center'}}>{button('Share image',()=>void act(()=>shareCard(cardData!,cardRef,false)),true)}{button('Save image',()=>void act(()=>shareCard(cardData!,cardRef,true)))}</View></>:contract?<>
   <View style={s.line}>{button('← Contracts',()=>{setContract(null);setConfirm(false);})}<Text style={s.kicker}>{contract.modifier.toUpperCase()}</Text></View>
   <ScrollView contentContainerStyle={{gap:10,alignItems:'center'}}><Text style={s.title}>{contract.name}</Text><MissionPreview key={contract.id} mission={contract.level.mission} definition={contract.level} size={Math.min(width-80,Math.max(90,(height-440)*.6),190)}/><Text style={s.body}>{contract.objective}</Text><Text style={s.muted}>Same map and tools in both modes. Score up to 10,000 points for speed and remaining charge.</Text>{confirm&&<View style={s.summary}><Text style={s.white}>Use a ranked attempt?</Text><Text style={[s.body,{marginTop:5}]}>Starting uses 1 of 5 attempts. Losing, leaving or running out of time also uses it. You cannot buy more. Ends Monday 00:00 UTC.</Text></View>}</ScrollView>
   <Text style={s.muted}>{data?.authenticated?Math.max(0,5-(data.attempts[contract.id]??0)):'Sign in to see'} ranked attempts left · practice is unlimited</Text><View style={{flexDirection:'row',gap:8,justifyContent:'center'}}>{button('Practice',()=>start(contract,true))}{button(confirm?'Confirm ranked start':'Play ranked',()=>confirm?start(contract,false):setConfirm(true),true,(data?.attempts[contract.id]??0)>=5||!!data?.active)}</View>
  </>:<>
   <View style={s.line}><Text style={s.kicker}>{local?'LOCAL TEST LEAGUE':'WEEKLY CONTRACTS'}</Text><Pressable accessibilityRole="button" accessibilityLabel="Refresh league" onPress={()=>void act(state.refresh)} style={{padding:6}}><Text style={s.muted}>{busy?'Loading…':weeklyResetLabel(state.window.endsAt,now)+' ↻'}</Text></Pressable></View>
   <View style={s.segments}>{(['contracts','standings','history'] as const).map(key=><Pressable key={key} accessibilityRole="tab" aria-selected={section===key} accessibilityState={{selected:section===key}} onPress={()=>setSection(key)} style={[s.segment,section===key&&{backgroundColor:'#37534B'}]}><Text style={s.white}>{key[0]!.toUpperCase()+key.slice(1)}</Text></Pressable>)}</View>
   <ScrollView style={{flex:1,minHeight:0}} contentContainerStyle={{gap:9,paddingBottom:8}}>
    {(state.pending||data?.active)&&<View style={s.summary}><Text style={s.white}>{state.pending?'Saved replay needs checking':`Previous attempt: ${data?.active?.status}`}</Text>{button('Check saved result',()=>void act(state.recover))}{data?.active?.status==='issued'&&button('Close previous attempt',()=>void act(state.abandon))}</View>}
    {!local&&!data?.authenticated&&button('Sign in to see your attempts',()=>void act(state.signIn),true)}
    {section==='contracts'?<><Text style={s.body}>Three routes. Five ranked attempts each. Your best escape on each counts.</Text>{data?.contracts.map(c=>{const best=personal?.best.find(b=>b.contract===c.id);return <Pressable key={c.id} accessibilityRole="button" accessibilityLabel={`Open contract ${c.name}`} onPress={()=>{setContract(c);setConfirm(false);}} style={s.contract}><Image source={arts[c.slot]} style={s.contractArt}/><View style={{flex:1,gap:4}}><Text style={s.kicker}>{c.district.toUpperCase()}</Text><Text style={s.white}>{c.name}</Text><Text style={s.muted}>{c.modifier} · {data.authenticated?`${Math.max(0,5-(data.attempts[c.id]??0))}/5 left`:'Sign in for attempts'}</Text><Text style={[s.muted,{color:best?'#D8EFAF':'#8AA39D'}]}>{best?`${best.points.toLocaleString()} best points`:'No ranked clear yet'}</Text></View><Text style={s.white}>›</Text></Pressable>;})}<View style={s.summary}><Text style={s.white}>{data?.earned?'Ghost Courier earned':'Earn Ghost Courier'}</Text><Text style={s.body}>Clear all three ranked contracts in a week. Keep the outfit and achievement forever.</Text>{data?.earned&&button('Equip earned outfit',()=>void act(async()=>{await state.equip();setMessage('Ghost Courier equipped.');}),true)}</View></>:section==='standings'?<>
     <View style={s.summary}><Text style={s.title}>{personal?local?'Your test score':`You’re #${personal.rank}`:'Unranked'}</Text><Text style={s.white}>{personal?.points.toLocaleString()??0} / 30,000 points · {personal?.cleared??0}/3</Text><Text style={s.body}>{local?'Only this browser’s results. Android ranks are server-verified.':data?.board.rival&&personal?data.board.rival.points>personal.points?`Another ${data.board.rival.points-personal.points} points matches #${data.board.rival.rank}; time breaks ties.`:`${((personal.ticks-data.board.rival.ticks)/30).toFixed(2)}s faster matches #${data.board.rival.rank}.`:personal?'You share the top rank. Keep your best escape.':'Complete a ranked contract to join.'}</Text>{personal&&button('Share my Courier Card',()=>setCard(data!.board),true)}</View>
     {!!data?.board.nearby.length&&<><Text style={s.kicker}>AROUND YOU</Text>{data.board.nearby.map(r=>row(r,personal))}</>}<Text style={s.kicker}>TOP COURIERS</Text>{data?.board.entries.length?data.board.entries.map(r=>row(r,personal)):<Text style={s.body}>No ranked clears this week yet.</Text>}
    </>:<><Text style={s.body}>Weekly ranks reset. Your earned outfit and completed seasons stay.</Text>{data?.history.length?data.history.map(b=><View key={b.week} style={s.summary}><Text style={s.white}>Week of {b.week}</Text><Text style={s.body}>{local?'Local test':`Final rank #${b.personal?.rank}`} · {b.personal?.cleared}/3 cleared · {b.personal?.points.toLocaleString()} pts</Text>{button('View Courier Card',()=>setCard(b))}</View>):<Text style={s.muted}>Your completed weeks will appear here after results are finalized.</Text>}</>}
   </ScrollView>
   <Text style={s.muted}>Best per contract · points, then time · no token prizes</Text>
  </>}
  {!!(message||error)&&<Text accessibilityLiveRegion="polite" style={s.error}>{message||error}</Text>}
 </View>;
}
const s=StyleSheet.create({homeCard:{flexDirection:'row',alignItems:'center',gap:12,padding:13,backgroundColor:'#1B302F',borderRadius:17,borderWidth:1,borderColor:'#40625B',marginBottom:8},medal:{width:39,height:44,alignItems:'center',justifyContent:'center',backgroundColor:'#CFE6E4',borderRadius:12},kicker:{fontSize:9,fontWeight:'800',letterSpacing:1,color:'#AFD1C6'},homeTitle:{fontSize:16,fontWeight:'800',color:'#ECF4EC'},muted:{fontSize:10,lineHeight:15,color:'#9DB5B5'},white:{fontSize:13,fontWeight:'700',color:'#E4F0E8'},body:{fontSize:11,lineHeight:17,color:'#B5CAC4'},summary:{backgroundColor:'#172724',borderRadius:15,borderWidth:1,borderColor:'#36514A',padding:13,gap:6},title:{fontSize:23,fontWeight:'800',color:'#E7F5D8'},line:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},row:{flexDirection:'row',alignItems:'center',gap:12,padding:11,borderRadius:12,backgroundColor:'#151F23',borderWidth:1,borderColor:'#263538'},yourRow:{borderColor:'#789F90',backgroundColor:'#21362F'},rankNumber:{width:25,color:'#D9EAAA',fontSize:17,fontWeight:'800'},button:{minHeight:41,paddingHorizontal:13,paddingVertical:10,borderRadius:11,backgroundColor:'#283D37',justifyContent:'center',alignItems:'center'},primary:{backgroundColor:'#CFE6E4'},buttonText:{color:'#D7E9DC',fontSize:11,fontWeight:'800'},segments:{flexDirection:'row',backgroundColor:'#172523',borderRadius:11,padding:3},segment:{flex:1,paddingVertical:9,alignItems:'center',borderRadius:9},contract:{flexDirection:'row',gap:11,alignItems:'center',padding:10,minHeight:99,borderRadius:15,borderWidth:1,borderColor:'#344A43',backgroundColor:'#182620'},contractArt:{width:89,height:76,borderRadius:10},input:{borderWidth:1,borderColor:'#49655C',borderRadius:10,padding:10,color:'#E8F4EB',fontSize:13},error:{fontSize:11,lineHeight:16,color:'#F3CCA6',padding:6}});
