import React,{useState} from 'react';
import {Image,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {dailyMission,rivalGap} from '../../shared/daily';
import {weekWindow,weeklyResetLabel} from '../../shared/weekly';
import {getLevel} from '../game/level';
import {useDailyClock} from './useDailyClock';
import {useWeeklyBoard} from './useWeeklyBoard';
import {NAV_ICONS} from '../components/BottomTabs';
export type WeeklyState=ReturnType<typeof useWeeklyBoard>;
export function useWeekly(active=true){const now=useDailyClock(active),week=weekWindow(new Date(now));return {...useWeeklyBoard(week.week,active),now,window:week};}
export function WeeklyCard({state,onPress}:{state:ReturnType<typeof useWeekly>;onPress:()=>void}){
 const personal=state.board?.personal;
 return <Pressable accessibilityRole="button" accessibilityLabel="Open weekly leaderboard" onPress={onPress} testID="weekly-home-card" style={s.homeCard}><View style={s.medal}><Image source={NAV_ICONS.leaderboard} style={s.medalIcon}/></View><View style={{flex:1,gap:3}}><Text style={s.kicker}>THIS WEEK</Text><Text style={s.homeTitle}>{personal?(state.local?'Your practice score':`You’re ranked #${personal.rank}`):'Climb the leaderboard'}</Text><Text style={s.muted}>{state.local?'Local practice · ':''}{weeklyResetLabel(state.window.endsAt,state.now)}</Text></View><Text style={{color:'#CFE6E4',fontSize:26}}>›</Text></Pressable>;
}
export default function WeeklyBoard({state,onPlay}:{state:ReturnType<typeof useWeekly>;onPlay:()=>void}){
 const [rules,setRules]=useState(false),{board,local,loading,error,now}=state,personal=board?.personal,today=getLevel(dailyMission(new Date(now)));
 return <View testID="weekly-leaderboard" style={{flex:1,minHeight:0,gap:10}}>
  <View style={s.summary}><View style={s.summaryTop}><Text style={s.kicker}>{local?'BROWSER PRACTICE':'WEEKLY STANDINGS'}</Text><Text style={s.muted}>{weeklyResetLabel(state.window.endsAt,now)}</Text></View><View style={s.scoreLine}><Text style={s.rank}>{local?(personal?personal.score.toLocaleString():'—'):personal?`#${personal.rank}`:'Unranked'}</Text><View style={{alignItems:'flex-end',gap:4}}><Text style={s.white}>{local?'Your weekly points':`${(personal?.score??0).toLocaleString()} pts`}</Text><Text style={s.muted}>{personal?.days??0} / 7 days cleared</Text></View></View><Text style={s.body}>{local?'Practice here. Verified online ranks are in the Android app.':personal?rivalGap(personal,board?.rival):'Finish today’s heist to join this week’s board.'}</Text></View>
  <Pressable accessibilityRole="button" accessibilityLabel={local?'Play today’s practice heist':'Play today’s ranked heist'} onPress={onPlay} style={s.play}><View><Text style={s.playTitle}>PLAY TODAY’S HEIST</Text><Text style={s.playSub}>{today.title} · best escape counts</Text></View><Text style={{color:'#163635',fontSize:25}}>↗</Text></Pressable>
  <View style={s.sectionLine}><Text style={s.white}>{local?'Your practice results':'Top couriers'}</Text><Pressable accessibilityRole="button" accessibilityLabel="Refresh weekly leaderboard" disabled={loading} onPress={()=>void state.refresh()} hitSlop={8} style={{minHeight:32,justifyContent:'center'}}><Text style={s.muted}>{loading?'Loading…':'Refresh ↻'}</Text></Pressable></View>
  {!!error&&<Text accessibilityLiveRegion="polite" style={s.body}>{error}</Text>}
  <ScrollView style={{flex:1,minHeight:40}} contentContainerStyle={{gap:6,paddingBottom:8}}>{board?.entries.length?board.entries.map(row=><View key={row.wallet} style={[s.row,row.wallet===personal?.wallet&&s.yourRow]}><Text style={[s.position,{color:row.rank<=3?'#D6EBA8':'#9EB4B4'}]}>{local?'•':String(row.rank).padStart(2,'0')}</Text><View style={{flex:1,gap:3}}><Text style={s.white}>{row.wallet===personal?.wallet?'You':`${row.wallet.slice(0,4)}…${row.wallet.slice(-4)}`}</Text><Text style={s.muted}>{row.days} day{row.days===1?'':'s'} · {row.seconds.toFixed(2)}s total</Text></View><Text style={s.white}>{row.score.toLocaleString()}</Text></View>):<View style={s.empty}><Image source={NAV_ICONS.leaderboard} style={{width:32,height:32,tintColor:'#AECBC5'}}/><Text style={s.white}>{loading?'Fetching standings…':error?'Standings unavailable':'Your first escape starts here.'}</Text><Text style={[s.body,{textAlign:'center'}]}>{local?'No daily practice clears this week.':error?'Refresh when you’re back online.':'No verified clears this week yet.'}</Text></View>}</ScrollView>
  <Pressable accessibilityRole="button" accessibilityState={{expanded:rules}} onPress={()=>setRules(!rules)} style={s.rules}><Text style={s.muted}>How weekly scoring works {rules?'−':'+'}</Text>{rules&&<Text style={[s.body,{marginTop:8}]}>Your best successful run each day adds to the weekly total. Higher points win; lower total time breaks ties. Exact ties share rank. Routes change at 00:00 UTC; weeks reset Monday. Unlimited retries with campaign access. No token prizes in this mode.</Text>}</Pressable>
 </View>;
}
const s=StyleSheet.create({homeCard:{flexDirection:'row',alignItems:'center',gap:12,padding:13,backgroundColor:'#1B302F',borderRadius:17,borderWidth:1,borderColor:'#40625B',marginBottom:8},medal:{width:39,height:44,alignItems:'center',justifyContent:'center',backgroundColor:'#CFE6E4',borderRadius:12},medalIcon:{width:24,height:24,tintColor:'#1B3835'},kicker:{fontSize:9,fontWeight:'800',letterSpacing:1.3,color:'#AFD1C6'},homeTitle:{fontSize:16,fontWeight:'800',color:'#ECF4EC'},muted:{fontSize:10,lineHeight:15,color:'#9DB5B5'},white:{fontSize:13,fontWeight:'700',color:'#E4F0E8'},body:{fontSize:11,lineHeight:17,color:'#B5CAC4'},summary:{backgroundColor:'#172724',borderRadius:19,borderWidth:1,borderColor:'#36514A',padding:15,gap:8},summaryTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},scoreLine:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},rank:{fontSize:35,lineHeight:44,fontWeight:'800',color:'#E7F5D8'},play:{minHeight:62,paddingHorizontal:16,paddingVertical:10,borderRadius:14,backgroundColor:'#CFE6E4',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},playTitle:{fontSize:12,fontWeight:'900',color:'#183735',letterSpacing:.5},playSub:{fontSize:10,color:'#3D5F5C',marginTop:4},sectionLine:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},row:{flexDirection:'row',alignItems:'center',gap:12,padding:12,borderRadius:12,backgroundColor:'#151F23',borderWidth:1,borderColor:'#263538'},yourRow:{borderColor:'#789F90',backgroundColor:'#21362F'},position:{width:24,fontSize:16,fontWeight:'800'},empty:{alignItems:'center',justifyContent:'center',flex:1,minHeight:112,gap:8,padding:12},rules:{paddingVertical:8,borderTopWidth:1,borderColor:'#273638'}});
