import React,{useRef,useState} from 'react';
import {Text,View} from 'react-native';
import Panel,{Button,ui} from '../playtest/Panel';
import {changePlaytest,finish,usePlaytest} from '../playtest/store';
import {localEntry} from '../playtest/tickets';
import {paidStore} from './store';
import type {PaidPlay} from './recovery';
export default function PaidPanel({visible,onClose,onStart}:{visible:boolean;onClose:()=>void;onStart:(p:PaidPlay)=>void}){const state=usePlaytest(),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),lock=useRef(false),entry=state.entry;
 async function act(fn:()=>Promise<void>|void){if(lock.current)return;lock.current=true;setBusy(true);try{await fn();setMessage('');}catch(e){setMessage(String(e));}finally{lock.current=false;setBusy(false);}}
 async function start(){if(!entry)return;let active=entry;if(!active.run){const startKey=await paidStore.prepare(active),now=new Date().toISOString();active={...active,status:'running',run:{id:crypto.randomUUID(),wallet:active.wallet,startKey,manifest:active.manifest,issuedAt:now,expiresAt:new Date(Date.now()+420000).toISOString(),result:null}};const next=active;changePlaytest(s=>{if(s.entry?.id!==next.id)throw new Error('The active entry changed.');return {...s,entry:next};});}const saved=await paidStore.open(active);onStart({entry:active,replay:saved.replay});}
 return <Panel visible={visible} title="Entry challenge" onClose={onClose}><Text style={ui.label}>LOCAL PLAYTEST · {state.balance} CREDITS</Text><Text style={ui.title}>Previous entry receipts.</Text><View style={ui.card}><Text style={ui.body}>Battery Dash · standard outfit and equipment</Text><Text style={ui.body}>Entry: 10 local credits. Escape: 10 credits returned. Capture, timeout or abandoning a started run: no return. This mode is separate from unlimited campaign retries.</Text><Text style={ui.body}>The clock allows 4 minutes of gameplay and 7 minutes total after Start. Pausing does not extend the deadline. Save / leave preserves the last completed input save.</Text><Text style={ui.body}>No real SKR, network fees, wallet approvals or cash rewards.</Text></View>
 {!entry?<Text style={ui.body}>New per-run entries are retired. Your campaign includes unlimited retries. Previous receipts remain below.</Text>:<View style={ui.card}><Text style={ui.body}>Entry {entry.id.slice(0,8)} · {entry.run?'Started · saved run available':'Ready · not started'}</Text><Button label={entry.run?'Resume saved entry':'Start entry challenge'} disabled={busy} onPress={()=>void act(start)}/>{!entry.run?<Button label="Cancel unstarted entry · return 10 credits" disabled={busy} onPress={()=>void act(()=>{changePlaytest(s=>s.entry?.id===entry.id?{...s,entry:null,balance:s.balance+10,receipts:[{id:'cancel:'+entry.id,label:'Unstarted entry cancelled',amount:10},...s.receipts]}:s);})}/>:<Button label="Abandon started entry · no return" disabled={busy} onPress={()=>void act(()=>{changePlaytest(s=>finish(s,{id:entry.id,kind:'entry',day:new Date().toISOString().slice(0,10),status:'abandoned',score:0,seconds:0,returned:0}));})}/>}</View>}
 {!!message&&<Text accessibilityLiveRegion="polite" style={ui.body}>{message}</Text>}<Text style={ui.label}>YOUR LOCAL ENTRY HISTORY</Text>{state.results.filter(r=>r.kind==='entry').slice(0,8).map(r=><Text key={r.id} style={ui.body}>{r.status} · {r.score} points · {r.returned} credits returned</Text>)}{!state.results.some(r=>r.kind==='entry')&&<Text style={ui.body}>Your completed attempts will appear here.</Text>}</Panel>;}
