import React from 'react';
import {Image,ImageBackground,Pressable,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {CAMPAIGN_OFFER} from '../../shared/economy';
export default function Paywall({local,stage,trialAvailable,busy,message,onBuy,onCancel,onTrial,onBack}:{local:boolean;stage:'offer'|'review'|'cancelled';trialAvailable:boolean;busy?:boolean;message?:string;onBuy:()=>void;onCancel:()=>void;onTrial:()=>void;onBack:()=>void}){
 const {height}=useWindowDimensions(),compact=height<720,currency=local?'test credits':'TEST SKR';
 return <View style={s.page}><View style={[s.card,{gap:compact?10:16,padding:compact?18:24}]}>
  <ImageBackground source={require('../../assets/world-v3/hideout.png')} style={[s.art,{height:compact?110:190}]} imageStyle={{borderRadius:20}} resizeMode="cover"><View style={s.shade}><Text style={s.kicker}>STEAL A SEEKER  /  {local?'LOCAL TEST':'DEVNET'}</Text><Image source={require('../../assets/visual-v2/courier-portrait-v2.png')} resizeMode="contain" style={{position:'absolute',right:2,bottom:0,width:95,height:115,opacity:.85}}/><Text style={[s.artTitle,{maxWidth:'79%'}]}>THE WHOLE{ '\n'}HEIST IS YOURS.</Text></View></ImageBackground>
  <View><Text style={[s.title,{fontSize:compact?25:32}]}>{stage==='cancelled'?'Try one escape first.':stage==='review'?'Your campaign pass.':'12 phones. One way out.'}</Text><Text style={s.body}>{stage==='cancelled'?'Payment not completed? Take one practice run, then decide.': 'Sneak in, take the phone, beat the patrols. Buy once and keep trying.'}</Text></View>
  {stage==='cancelled'?<View style={s.terms}><Text style={s.white}>{trialAvailable?'One free attempt · first mission':'Your free attempt has been used'}</Text><Text style={s.body}>No wallet approval. Practice does not unlock levels, rank, or earn a rebate. Leaving or restarting ends the trial.</Text></View>:<>
   <View style={s.priceRow}><View><Text style={s.price}>{CAMPAIGN_OFFER.price}<Text style={s.unit}> {currency}</Text></Text><Text style={s.small}>ONE PAYMENT · NO SUBSCRIPTION</Text></View><View style={s.badge}><Text style={s.badgeText}>ALL 12{ '\n'}MISSIONS</Text></View></View>
   <View style={s.features}>{['Unlimited retries','Saved phone collection','Daily runs included'].map(t=><Text key={t} style={s.feature}>✓ {t}</Text>)}</View>
   <View style={s.terms}><Text style={s.white}>Finish all 12. Get {CAMPAIGN_OFFER.rebate} {currency} back.</Text><Text style={s.body}>{local?'One local rebate after completing the campaign.':'One rebate to the purchasing wallet after server verification of all 12 wins. Funds reserved before approval.'} You pay {CAMPAIGN_OFFER.price}; total rebate is {CAMPAIGN_OFFER.rebate}. It does not cover the full price.</Text></View>
  </>}
  <Text style={s.small}>{local?'Browser-only credits. No real money or wallet transactions.':'Devnet tokens have no monetary value. Wallet shows the additional devnet SOL network fee before approval.'} Outfits are separate, optional purchases.</Text>
  {!!message&&<Text accessibilityLiveRegion="polite" style={s.error}>{message}</Text>}
  <Pressable accessibilityRole="button" accessibilityLabel={stage==='cancelled'&&trialAvailable?'Play free trial':stage==='review'?`Confirm campaign · ${CAMPAIGN_OFFER.price} ${currency}`:local?`Buy campaign · ${CAMPAIGN_OFFER.price} playtest credits`:'Connect / buy campaign'} disabled={busy} onPress={stage==='cancelled'?(trialAvailable?onTrial:onBack):onBuy} style={[s.primary,busy&&{opacity:.5}]}><Text style={s.primaryText}>{busy?'PLEASE WAIT…':stage==='cancelled'?(trialAvailable?'PLAY ONE FREE RUN ↗':'BACK TO CAMPAIGN'):stage==='review'?`CONFIRM ${CAMPAIGN_OFFER.price} ${currency.toUpperCase()} ↗`:local?'UNLOCK CAMPAIGN ↗':'CONNECT / BUY CAMPAIGN ↗'}</Text></Pressable>
  <Pressable accessibilityRole="button" accessibilityLabel={stage==='cancelled'?'Back to campaign offer':stage==='review'?'Cancel payment':'Not now'} onPress={stage==='cancelled'?onBack:onCancel} disabled={busy} style={{padding:8}}><Text style={s.secondary}>{stage==='cancelled'?'Back to campaign offer':stage==='review'?'Cancel payment':'Not now'}</Text></Pressable>
 </View></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#090D11',alignItems:'center',justifyContent:'center'},card:{width:'100%',maxWidth:440},art:{overflow:'hidden',borderRadius:20},shade:{flex:1,padding:18,backgroundColor:'#07111570',justifyContent:'space-between'},kicker:{color:'#BAF8DD',fontSize:9,fontWeight:'800',letterSpacing:1.5},artTitle:{color:'#FCFFF5',fontSize:27,fontWeight:'900',letterSpacing:-1},title:{color:'#F5F5E9',fontWeight:'900',letterSpacing:-1},body:{color:'#AFBDC3',fontSize:12,lineHeight:18,marginTop:5},priceRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},price:{fontSize:39,fontWeight:'900',color:'#E9FFF3'},unit:{fontSize:15,fontWeight:'600'},small:{color:'#869BA5',fontSize:10,lineHeight:15},badge:{backgroundColor:'#D3FCE514',padding:10,borderWidth:1,borderColor:'#557869',borderRadius:12},badgeText:{color:'#C6F5DE',fontSize:11,fontWeight:'900',textAlign:'center'},features:{flexDirection:'row',flexWrap:'wrap',gap:8},feature:{color:'#D3E6DB',fontSize:10},terms:{backgroundColor:'#17282B',borderColor:'#385A58',borderWidth:1,borderRadius:14,padding:12},white:{color:'#D6FBEA',fontSize:13,fontWeight:'800'},primary:{backgroundColor:'#C4F7DC',padding:17,borderRadius:13},primaryText:{fontSize:12,fontWeight:'900',color:'#133229',textAlign:'center'},secondary:{color:'#B3C5CE',fontSize:12,textAlign:'center'},error:{color:'#F9C6A6',fontSize:11,lineHeight:16}});
