const $=id=>document.getElementById(id);
let data,selected=0,tick=0,playing=false,previous=0;
const materials=['warehouse','rooftop','vault'].map(name=>{const i=new Image();i.src=name+'-cap.jpg';i.onload=()=>data&&draw();return i;});
const ctx=$('map').getContext('2d'),fmt=n=>Number(n).toFixed(1),pressure=n=>'<span class="pressure" aria-label="'+n+' out of 5">'+[1,2,3,4,5].map(i=>'<i class="'+(i<=n?'on':'')+'"></i>').join('')+'</span>';
function choose(n){selected=n;tick=0;playing=false;$('play').textContent='Play replay';const d=data.levels[n],r=d.report,j=r.judgment,s=r.solution;
 $('levels').querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-selected',String(i===n)));
 $('detail').innerHTML='<small>MISSION '+String(n+1).padStart(2,'0')+' / '+j.label+'</small><h2>'+r.title+'</h2><div class="pills"><span class="pill">'+s.hp+'/100 HP</span><span class="pill">'+fmt(s.seconds)+' s</span><span class="pill">'+s.kills+' guards disabled</span><span class="pill">'+s.taps+' taps</span></div><p>'+j.reason+'</p><h3>Controlled attempts</h3>'+Object.entries(r.profiles).map(([k,p])=>'<div class="barrow"><span>'+({direct:'No shooting',reactive:'Basic shooting',slow:'Slower shooting',mild:'Mild plan delay',coarse:'Larger plan delay'}[k])+'</span><span class="bar"><i style="width:'+p.winRate+'%"></i></span><b>'+p.wins+'/'+p.runs+'</b></div>').join('')+'<p class="smallnote">A timeout counts as a failed run, not a death. Delayed plans cannot correct their route when they fall behind.</p><div class="proposal"><small>ONE PROPOSED EXPERIMENT</small><p>'+j.experiment+'</p></div><div class="pills"><span class="pill">Damage before pickup: '+s.beforePickupDamage+'</span><span class="pill">After pickup: '+s.afterPickupDamage+'</span></div><a class="button" href="/?build=difficulty-audit&testMission='+r.id+'">Try mission '+(n+1)+'</a><div class="timeline" aria-label="Winning run events">'+d.solution.events.map(e=>'<div class="event"><b>'+fmt(e.tick/30)+' s</b><span>'+({pickup:'Phone taken · '+e.hp+' HP',delivery:'Phone delivered · '+e.hp+' HP',switch:'Switch activated',kill:'Guard disabled · '+e.total+' total',damage:'−'+e.amount+' HP · '+(e.alarm?'during alarm':'before pickup')}[e.type])+'</span></div>').join('')+'</div>';
 draw();
}
function rounded(x,y,w,h,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,.07);ctx.fill();}
function draw(){if(!data)return;const d=data.levels[selected],l=d.level,samples=d.solution.samples,last=samples[samples.length-1],s=samples.find(p=>p.tick>=tick)||last,di=Math.min(2,Math.floor(selected/4)),m=materials[di];
 ctx.setTransform(40,0,0,40,0,0);ctx.clearRect(0,0,12,20);ctx.fillStyle=['#27312e','#33424c','#454a45'][di];ctx.fillRect(0,0,12,20);
 ctx.lineWidth=.015;ctx.strokeStyle='#78938624';for(let x=0;x<=12;x++){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,20);ctx.stroke();}for(let y=0;y<=20;y++){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(12,y);ctx.stroke();}
 for(const b of l.blockers){rounded(b.x+.05,b.y+.12,b.w,b.h,'#09110db0');rounded(b.x,b.y,b.w,b.h,'#34423c');if(b.kind==='wall'&&b.x>.64&&b.y>.64&&b.x+b.w<11.36&&b.y+b.h<19.36&&m.complete){const cols=Math.ceil(b.w/2),rows=Math.ceil(b.h/2);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)ctx.drawImage(m,b.x+x*b.w/cols,b.y+y*b.h/rows,b.w/cols,b.h/rows-.04);}else if(b.kind!=='wall'){ctx.strokeStyle='#92aaa177';ctx.lineWidth=.06;ctx.strokeRect(b.x+.08,b.y+.08,b.w-.16,b.h-.16);}}
 // Power gate is reconstructed from the recorded switch event.
 for(const g of l.gates||[]){if(g.mode==='power'&&d.solution.events.some(e=>e.type==='switch'&&e.tick<=tick))continue;rounded(g.box.x,g.box.y,g.box.w,g.box.h,'#c3a869');}
 const e=l.exit;rounded(e.x,e.y,e.w,e.h,'#397362');ctx.fillStyle='#d9ffec';ctx.font='.24px system-ui';ctx.textAlign='center';ctx.fillText('EXIT',e.x+e.w/2,e.y+e.h/2+.08);
 ctx.strokeStyle='#d7edbb55';ctx.lineWidth=.045;ctx.beginPath();samples.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();
 if($('heat').checked){const deaths=[...d.report.trials.reactive,...d.report.trials.slow].filter(r=>r.death);for(const r of deaths){ctx.fillStyle='#ff554b22';ctx.beginPath();ctx.arc(r.death.x,r.death.y,.42,0,Math.PI*2);ctx.fill();}}
 for(const sw of l.switches||[]){rounded(sw.x-.2,sw.y-.2,.4,.4,'#d6ac59');}
 (l.targets||[l.phone]).forEach((p,i)=>{if(i<s.delivered||i===s.delivered&&s.carrying)return;rounded(p.x-.14,p.y-.28,.28,.56,'#dcf4e9');rounded(p.x-.10,p.y-.22,.20,.43,'#244a40');});
 s.guards.forEach((g,i)=>{if(!g.active||g.hp<=0)return;ctx.fillStyle=g.phase==='aim'||g.phase==='fire'?'#fa8d70':'#e3c289';ctx.beginPath();ctx.arc(g.x,g.y,.25,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#1f2821';ctx.lineWidth=.08;ctx.stroke();ctx.fillStyle='#142820';ctx.font='bold .19px system-ui';const role=l.patrols[i].combatRole;ctx.fillText(role==='warden'?'W':role==='heavy'?'H':role==='sentry'?'S':'',g.x,g.y+.07);ctx.strokeStyle='#e3c28988';ctx.lineWidth=.025;ctx.beginPath();ctx.moveTo(g.x,g.y);ctx.lineTo(g.x+Math.cos(g.angle)*.65,g.y+Math.sin(g.angle)*.65);ctx.stroke();});
 ctx.fillStyle='#eaf5ed';ctx.beginPath();ctx.arc(s.x,s.y,.30,0,Math.PI*2);ctx.fill();ctx.fillStyle='#75cbb2';ctx.beginPath();ctx.arc(s.x,s.y,.13,0,Math.PI*2);ctx.fill();if(s.carrying)rounded(s.x+.15,s.y-.25,.13,.24,'#efffbc');
 ctx.setTransform(1,0,0,1,0,0);$('time').textContent=fmt(tick/30)+' / '+fmt(last.tick/30)+'s';$('seek').value=tick/last.tick*1000;$('status').textContent=tick>=last.tick?'Verified escape · '+s.hp+' HP remaining':s.carrying?'PHONE TAKEN · '+s.hp+' HP':s.hp+' HP · approach';
}
function animate(ts){const elapsed=previous?Math.min(.1,(ts-previous)/1000):0;previous=ts;if(playing&&data){const a=data.levels[selected].solution.samples,max=a[a.length-1].tick;tick=Math.min(max,tick+elapsed*30*Number($('speed').value));if(tick>=max){playing=false;$('play').textContent='Play replay';}draw();}requestAnimationFrame(animate);}
$('play').onclick=()=>{if(!data)return;const a=data.levels[selected].solution.samples;if(tick>=a[a.length-1].tick)tick=0;playing=!playing;$('play').textContent=playing?'Pause replay':'Play replay';};$('restart').onclick=()=>{tick=0;draw();};$('seek').oninput=()=>{const a=data.levels[selected].solution.samples;tick=Number($('seek').value)/1000*a[a.length-1].tick;draw();};$('heat').onchange=draw;
fetch('data.json').then(r=>{if(!r.ok)throw Error('Could not load audit data');return r.json();}).then(d=>{data=d;
 $('table').innerHTML=d.levels.map(({report:r},i)=>'<tr data-level="'+i+'"><td><b>'+String(i+1).padStart(2,'0')+' · '+r.title+'</b></td><td>'+pressure(r.judgment.pressure)+'</td><td>'+fmt(r.solution.seconds)+' s</td><td>'+r.solution.hp+'/100</td><td>'+(r.profiles.reactive.wins+r.profiles.slow.wins)+'/48</td><td class="'+(r.judgment.action==='Keep'?'keep':'ease')+'">'+r.judgment.action+'</td></tr>').join('');
 $('table').querySelectorAll('tr').forEach(row=>{row.onclick=()=>{choose(Number(row.dataset.level));$('viewer').scrollIntoView({behavior:'smooth'});};});
 $('levels').innerHTML=d.levels.map((_,i)=>'<button aria-label="Inspect mission '+(i+1)+'" aria-selected="false">'+String(i+1).padStart(2,'0')+'</button>').join('');$('levels').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>choose(i));
 $('method').innerHTML='<ul>'+Object.entries(d.report.profiles).map(([k,v])=>'<li><b>'+k+'</b>: '+v+'</li>').join('')+'</ul>';
 $('source').textContent='Audited commit '+d.report.commit.slice(0,7)+' · Rules '+d.report.rules.rulesHash+' · Generated '+new Date(d.report.generatedAt).toLocaleString()+'. Balance changes: none.';choose(0);requestAnimationFrame(animate);
}).catch(e=>{$('source').textContent=e.message;});
