import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyInventory,earnCredits,redeemCredits,creditReward,CREDIT_PACKS} from '../shared/store';
import {priceProduct} from '../server/pricing';
import {networkConfig} from '../server/network';
test('campaign credits reward first clears and only newly earned stars',()=>{let s=emptyInventory();s=earnCredits(s,'practice',1);assert.equal(s.balance,100);assert.strictEqual(earnCredits(s,'practice',1),s);s=earnCredits(s,'practice',3);assert.equal(s.balance,150);assert.strictEqual(earnCredits(s,'practice',2),s);assert.equal(creditReward(4),0);assert.strictEqual(earnCredits(s,'practice',999),s);for(let n=2;n<=12;n++)s=earnCredits(s,String(n),3);assert.equal(s.balance,1800);});
test('local store atomically debits once and equips; insufficient funds are unchanged',()=>{const s=emptyInventory();assert.throws(()=>redeemCredits(s,'night-courier'),/Not enough/);assert.equal(s.balance,0);const funded={...s,balance:500},bought=redeemCredits(funded,'night-courier');assert.equal(bought.balance,200);assert.equal(bought.equipment.outfit,'night-courier');assert.strictEqual(redeemCredits(bought,'night-courier'),bought);assert.throws(()=>redeemCredits(bought,'signal-runner'));});
test('live pass has two distinct choices and testing reduces both',()=>{const now=Date.now(),rates={SKR:'0.02',SOL:'100',at:now};const live=networkConfig({}),testing=networkConfig({TEST_PRICING:'true'});assert.equal(live.passSkr,500);assert.equal(testing.passSkr,1);assert.equal(priceProduct('campaign','SKR',rates,6,now,1,1000,{},live.passSkr).amount,'500000000');assert.equal(priceProduct('campaign','SOL',rates,6,now,1,1000,{},live.passSkr).amount,'100000000');assert.equal(priceProduct('campaign','SKR',rates,6,now,100,10,{},testing.passSkr).amount,'1000000');});
test('credit pack quote uses dollars, never its credited quantity or cosmetic token price',()=>{const now=Date.now(),rates={SKR:'0.02',SOL:'100',at:now};for(const p of CREDIT_PACKS){const sol=priceProduct(p.id,'SOL',rates,6,now);assert.equal(sol.usdCents,p.usdCents);const testPrice=priceProduct(p.id,'SKR',rates,6,now,100);assert(BigInt(testPrice.amount)<BigInt(priceProduct(p.id,'SKR',rates,6,now).amount));}});
