import React,{useState} from 'react';
import {Platform,Pressable,Share,Switch,Text,View} from 'react-native';
import {clearReport,reportJson,setRecording,usePlaytestLog} from './store';
import {summarize} from './model';
export default function PlaytestControls(){const {log,ready,error}=usePlaytestLog(),[message,setMessage]=useState(''),summary=summarize(log.runs);
 async function share(){try{const text=reportJson();if(Platform.OS==='web'){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='seeker-playtest.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}else await Share.share({message:text,title:'Steal a Seeker playtest report'});setMessage('Report ready. Share it only with people you choose.');}catch{setMessage('Could not export. Your report is still saved here.');}}
 const button=(label:string,fn:()=>void)=><Pressable accessibilityRole="button" accessibilityLabel={label} onPress={fn} style={{padding:13,borderRadius:10,backgroundColor:'#294139'}}><Text style={{color:'#dcece2',textAlign:'center'}}>{label}</Text></Pressable>;
 return <View style={{gap:12}}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><Text style={{color:'#dcece2',fontSize:16,flex:1}}>Local playtest recording</Text><Switch accessibilityLabel="Local playtest recording" disabled={!ready} value={log.enabled} onValueChange={setRecording}/></View><Text style={{color:'#adc8b8',fontSize:12,lineHeight:19}}>Optional. Saves the last 100 attempts on this device: outcomes, tools, failure tiles and performance. No wallet addresses. Nothing uploads automatically. Turning off stops new recording; delete clears the report.</Text><Text style={{color:'#dcece2'}}>{summary.attempts} attempts · {summary.wins} escapes · {summary.retries} consecutive retries</Text>{button('Export playtest report',()=>void share())}{button('Delete report and stop recording',()=>{clearReport();setMessage('Local report deleted. Recording is off.');})}{!!(error||message)&&<Text accessibilityLiveRegion="polite" style={{color:'#adc8b8'}}>{error||message}</Text>}</View>;
}
