import type {WalletNames} from './wallet-names';
import {paymentDiagnostic,unavailableMessage} from './payment-errors';
import {registerSite} from './site';
import {STORE_ITEMS,RETIRED_ITEMS} from '../shared/store';
import {CampaignService} from './campaign-service';
import {LEVEL_PAGE} from './campaign-levels';
import {CAMPAIGN_IDS,type MissionId} from '../src/game/level';
import Fastify from 'fastify';
import rateLimit from '@fastify/rate-limit';
import {z,ZodError} from 'zod';
import {address,signature as validateSignature} from '@solana/kit';
import {CREDIT_PACKS} from '../shared/store';
import {CAMPAIGN_USD_CENTS} from '../shared/pricing';
import {PRODUCTS,PASS_BUNDLE,type ProductId} from '../shared/commerce';
import {progressInput} from './progress';
import {CommerceService,ServiceError} from './service';
import {ReturnService,returnStatus} from './returns';
const wallet=z.string().refine(v=>{try{address(v);return true;}catch{return false;}}),uuid=z.string().uuid(),sku=z.enum(PRODUCTS.map(p=>p.id) as [ProductId,...ProductId[]]);
const bytes=z.string().max(8192).regex(/^[A-Za-z0-9+/]*={0,2}$/);
export async function createApp(service:CommerceService,names?:WalletNames){
 const campaign=new CampaignService(service.pool,service.campaignReturns??new ReturnService(service.pool,undefined,{mint:service.config.mint,treasury:service.config.recipient,source:service.config.destination,decimals:service.config.decimals,cluster:service.config.cluster}));
 const app=Fastify({bodyLimit:16*1024,logger:{level:'warn',redact:['req.headers.authorization','req.body.code','req.body.promotionCode']}});await app.register(rateLimit,{max:180,timeWindow:'1 minute'});
 app.setErrorHandler((error,req,reply)=>{if(error instanceof ZodError)return reply.code(400).send({error:'Invalid request.'});if(error instanceof ServiceError){if(error.status>=500)req.log.error({diagnostic:error.diagnostic??error.message,route:req.routeOptions.url},'Payment service unavailable');return reply.code(error.status).send({error:error.message});}const e=error as {statusCode?:number};if(e.statusCode&&e.statusCode<500)return reply.code(e.statusCode).send({error:'Request could not be accepted.'});req.log.error({diagnostic:paymentDiagnostic(error),route:req.routeOptions.url},'Request failed');return reply.header('Retry-After','5').code(503).send({error:unavailableMessage(req.routeOptions.url??req.url)});});
 async function account(header:string|undefined){if(!header?.startsWith('Bearer '))throw new ServiceError(401,'Wallet sign-in required.');const token=header.slice(7);if(!/^[0-9a-f]{64}$/.test(token))throw new ServiceError(401,'Invalid session.');return {wallet:await service.authenticate(token),token};}
 registerSite(app);
 app.get('/health',async()=>{await service.pool.query('SELECT 1');return {ok:true,cluster:service.config.cluster??'solana:devnet'};});
 app.get('/health/payments',async()=>{await service.paymentReady();await service.pricing('campaign');return {ok:true,cluster:service.config.cluster??'solana:devnet'};});
 const code=z.string().trim().min(4).max(64).regex(/^[A-Za-z0-9_-]+$/);
 app.post('/promotions/preview',{config:{rateLimit:{max:15,timeWindow:'1 minute'}}},async req=>{const b=z.object({code,sku}).strict().parse(req.body);return service.previewPromotion(b.code,b.sku);});
 app.post('/promotions/claim',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async req=>{const a=await account(req.headers.authorization),b=z.object({code,sku}).strict().parse(req.body);return service.claimPromotion(a.wallet,b.code,b.sku);});
 app.get('/pricing/:sku',async req=>service.pricing(z.object({sku}).parse(req.params).sku));
 app.post('/orders/:id/cancel',async req=>service.cancelQuote((await account(req.headers.authorization)).wallet,z.object({id:uuid}).parse(req.params).id));
 app.get('/catalog',async()=>({testPricing:service.config.testPricing??false,creditStore:STORE_ITEMS.filter(i=>!RETIRED_ITEMS.includes(i.id)).map(i=>({...i,price:service.config.storeCreditPrices?.[i.id]??i.price})),cluster:service.config.cluster??'solana:devnet',disclaimer:service.config.cluster==='solana:mainnet'?(service.config.testPricing?'Mainnet test: payments use real money.':'Mainnet: payments use real money.'):'Test tokens have no monetary value.',...(service.config.usdPricing?{paymentCurrencies:['SKR','SOL'],products:PRODUCTS.filter(p=>!RETIRED_ITEMS.includes(p.id)).map(({price,...product})=>({...product,...(product.id==='campaign'?{usdCents:service.config.campaignUsdCents??CAMPAIGN_USD_CENTS/(service.config.priceDivisor??1),skrPrice:service.config.passSkr}:product.kind==='credits'?{credits:CREDIT_PACKS.find(p=>p.id===product.id)!.credits,usdCents:service.config.creditPackPrices?.[product.id]??CREDIT_PACKS.find(p=>p.id===product.id)!.usdCents/(service.config.priceDivisor??1)}:{skrPrice:service.config.shopPrices?.[product.id]??price/(service.config.priceDivisor??1)})}))}:{currency:'TEST SKR',products:PRODUCTS.filter(p=>!RETIRED_ITEMS.includes(p.id))})}));
 app.post('/auth/challenge',async req=>service.challenge(z.object({wallet}).strict().parse(req.body).wallet));
 app.post('/auth/verify',async req=>service.signIn(z.object({id:uuid,wallet,signedMessage:bytes,signature:bytes}).strict().parse(req.body)));
 app.post('/auth/logout',async req=>{const a=await account(req.headers.authorization);await service.logout(a.token);return {ok:true};});
 app.post('/credits/redeem',async req=>{const b=z.object({sku:z.string().max(40),expectedPrice:z.number().int().positive().max(100000).optional()}).strict().parse(req.body);return service.redeem((await account(req.headers.authorization)).wallet,b.sku,b.expectedPrice);});
 app.get('/me',async req=>service.me((await account(req.headers.authorization)).wallet));
 app.get('/returns/:id',async req=>returnStatus(service.pool,(await account(req.headers.authorization)).wallet,z.object({id:uuid}).parse(req.params).id));
 app.get('/orders',async req=>service.orders((await account(req.headers.authorization)).wallet));
 app.post('/orders',async req=>{const a=await account(req.headers.authorization),b=z.object({sku,idempotencyKey:uuid,currency:z.enum(['SKR','SOL']).default('SKR'),promotionCode:code.optional()}).strict().parse(req.body);return service.createOrder(a.wallet,b.sku,b.idempotencyKey,b.currency,b.promotionCode);});
 app.get('/orders/:id',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params);return service.getOrder(a.wallet,id);});
 app.post('/orders/:id/prepare',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params);z.object({}).strict().parse(req.body);return service.preparePayment(a.wallet,id);});
 app.post('/orders/:id/transaction',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params),body=z.object({signature:z.string().refine(v=>{try{validateSignature(v);return true;}catch{return false;}})}).strict().parse(req.body);return service.attach(a.wallet,id,body.signature);});
 app.post('/orders/:id/reconcile',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params);await service.getOrder(a.wallet,id);await service.reconcile(id);return service.getOrder(a.wallet,id);});
 app.put('/me/progress',async req=>service.syncProgress((await account(req.headers.authorization)).wallet,progressInput.parse(req.body)));
 app.put('/me/equipment',async req=>service.equip((await account(req.headers.authorization)).wallet,z.object({sku:z.union([sku,z.literal(PASS_BUNDLE.outfit)])}).strict().parse(req.body).sku));
 app.post('/me/unequip',async req=>service.unequip((await account(req.headers.authorization)).wallet,z.object({slot:z.enum(['outfit','trail','frame','rack'])}).strict().parse(req.body).slot));
 const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{try{return new Date(`${v}T00:00:00Z`).toISOString().slice(0,10)===v;}catch{return false;}}),rulesHash=z.string().regex(/^[a-f0-9]{64}$/);
 app.get('/campaign',async req=>campaign.summary((await account(req.headers.authorization)).wallet));
 app.get('/campaign/leaderboard',async req=>{const board=await campaign.leaderboard(req.headers.authorization?(await account(req.headers.authorization)).wallet:undefined);return names?names.enrich(board):board;});
 app.addHook('onClose',async()=>names?.close());
 app.post('/campaign/claim',async req=>{z.object({}).strict().parse(req.body);return campaign.claim((await account(req.headers.authorization)).wallet);});
 app.post('/campaign/runs',{bodyLimit:1024*1024,config:{rateLimit:{max:12,timeWindow:'1 minute'}}},async req=>{const a=await account(req.headers.authorization),b=z.object({mission:z.enum(CAMPAIGN_IDS as [MissionId,...MissionId[]]).optional(),level:z.number().int().min(13).max(1000000).optional(),rulesHash,replay:z.unknown()}).strict().refine(v=>(v.mission===undefined)!==(v.level===undefined),'Name one mission or one level.').parse(req.body);return campaign.submit(a.wallet,b.level!==undefined?{level:b.level}:{mission:b.mission!},b.rulesHash,b.replay);});
 // published levels are public and immutable, so clients may cache them by number
 app.get('/campaign/levels',async req=>{const q=z.object({from:z.coerce.number().int().min(13).default(13),to:z.coerce.number().int().min(13).optional()}).parse(req.query);const latest=await campaign.levels.latest();const to=Math.min(q.to??q.from+LEVEL_PAGE-1,q.from+LEVEL_PAGE-1);return {latest,levels:await campaign.levels.list(q.from,to)};});
 return app;
}
