import {registerSite} from './site';
import {RETIRED_ITEMS} from '../shared/store';
import {CampaignService} from './campaign-service';
import {CAMPAIGN_IDS,type MissionId} from '../src/game/level';
import Fastify from 'fastify';
import rateLimit from '@fastify/rate-limit';
import {z,ZodError} from 'zod';
import {address,signature as validateSignature} from '@solana/kit';
import {CREDIT_PACKS} from '../shared/store';
import {CAMPAIGN_USD_CENTS} from '../shared/pricing';
import {PRODUCTS,type ProductId} from '../shared/commerce';
import {progressInput} from './progress';
import {CommerceService,ServiceError} from './service';
import {RankedService} from './ranked-service';
import {LeagueService} from './league-service';
import {resolveSkr} from './skr-identity';
import {ReturnService,returnStatus} from './returns';
import {PaidService} from './paid-service';
const wallet=z.string().refine(v=>{try{address(v);return true;}catch{return false;}}),uuid=z.string().uuid(),sku=z.enum(PRODUCTS.map(p=>p.id) as [ProductId,...ProductId[]]);
const bytes=z.string().max(8192).regex(/^[A-Za-z0-9+/]*={0,2}$/);
export async function createApp(service:CommerceService,ranked=new RankedService(service.pool),paid=new PaidService(service.pool,service.chain,service.config,new ReturnService(service.pool,undefined,{mint:service.config.mint,treasury:service.config.recipient,source:service.config.destination,decimals:service.config.decimals,cluster:service.config.cluster}))){
 const league=new LeagueService(service.pool,ranked);
 const campaign=new CampaignService(service.pool,service.campaignReturns??new ReturnService(service.pool,undefined,{mint:service.config.mint,treasury:service.config.recipient,source:service.config.destination,decimals:service.config.decimals,cluster:service.config.cluster}));
 const app=Fastify({bodyLimit:16*1024,logger:{level:'warn',redact:['req.headers.authorization']}});await app.register(rateLimit,{max:180,timeWindow:'1 minute'});
 app.setErrorHandler((error,req,reply)=>{if(error instanceof ZodError)return reply.code(400).send({error:'Invalid request.'});if(error instanceof ServiceError)return reply.code(error.status).send({error:error.message});const e=error as {statusCode?:number};if(e.statusCode&&e.statusCode<500)return reply.code(e.statusCode).send({error:'Request could not be accepted.'});req.log.error({message:error instanceof Error?error.message:'Service error'},'Request failed');return reply.code(503).send({error:req.url.startsWith('/league')||req.url.startsWith('/runs')?'Competition service temporarily unavailable. Keep your saved run and retry.':'Service temporarily unavailable. Your payment will be reconciled; do not pay again.'});});
 async function account(header:string|undefined){if(!header?.startsWith('Bearer '))throw new ServiceError(401,'Wallet sign-in required.');const token=header.slice(7);if(!/^[0-9a-f]{64}$/.test(token))throw new ServiceError(401,'Invalid session.');return {wallet:await service.authenticate(token),token};}
 registerSite(app);
 app.get('/health',async()=>{await service.pool.query('SELECT 1');return {ok:true,cluster:service.config.cluster??'solana:devnet'};});
 app.get('/pricing/:sku',async req=>service.pricing(z.object({sku}).parse(req.params).sku));
 app.post('/orders/:id/cancel',async req=>service.cancelQuote((await account(req.headers.authorization)).wallet,z.object({id:uuid}).parse(req.params).id));
 app.get('/catalog',async()=>({cluster:service.config.cluster??'solana:devnet',disclaimer:service.config.cluster==='solana:mainnet'?'Mainnet test: payments use real money.':'Test tokens have no monetary value.',...(service.config.usdPricing?{paymentCurrencies:['SKR','SOL'],products:PRODUCTS.filter(p=>!RETIRED_ITEMS.includes(p.id)).map(({price,...product})=>({...product,...(product.id==='campaign'?{usdCents:service.config.campaignUsdCents??CAMPAIGN_USD_CENTS/(service.config.priceDivisor??1),skrPrice:service.config.passSkr}:product.kind==='credits'?{credits:CREDIT_PACKS.find(p=>p.id===product.id)!.credits,usdCents:CREDIT_PACKS.find(p=>p.id===product.id)!.usdCents/(service.config.priceDivisor??1)}:{skrPrice:service.config.shopPrices?.[product.id]??price/(service.config.priceDivisor??1)})}))}:{currency:'TEST SKR',products:PRODUCTS.filter(p=>!RETIRED_ITEMS.includes(p.id))})}));
 app.post('/auth/challenge',async req=>service.challenge(z.object({wallet}).strict().parse(req.body).wallet));
 app.post('/auth/verify',async req=>service.signIn(z.object({id:uuid,wallet,signedMessage:bytes,signature:bytes}).strict().parse(req.body)));
 app.post('/auth/logout',async req=>{const a=await account(req.headers.authorization);await service.logout(a.token);return {ok:true};});
 app.post('/credits/redeem',async req=>service.redeem((await account(req.headers.authorization)).wallet,z.object({sku:z.string().max(40)}).strict().parse(req.body).sku));
 app.get('/me',async req=>service.me((await account(req.headers.authorization)).wallet));
 app.get('/returns/:id',async req=>returnStatus(service.pool,(await account(req.headers.authorization)).wallet,z.object({id:uuid}).parse(req.params).id));
 app.get('/orders',async req=>service.orders((await account(req.headers.authorization)).wallet));
 app.post('/orders',async req=>{const a=await account(req.headers.authorization),b=z.object({sku,idempotencyKey:uuid,currency:z.enum(['SKR','SOL']).default('SKR')}).strict().parse(req.body);return service.createOrder(a.wallet,b.sku,b.idempotencyKey,b.currency);});
 app.get('/orders/:id',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params);return service.getOrder(a.wallet,id);});
 app.post('/orders/:id/prepare',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params);z.object({}).strict().parse(req.body);return service.preparePayment(a.wallet,id);});
 app.post('/orders/:id/transaction',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params),body=z.object({signature:z.string().refine(v=>{try{validateSignature(v);return true;}catch{return false;}})}).strict().parse(req.body);return service.attach(a.wallet,id,body.signature);});
 app.post('/orders/:id/reconcile',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params);await service.getOrder(a.wallet,id);await service.reconcile(id);return service.getOrder(a.wallet,id);});
 app.put('/me/progress',async req=>service.syncProgress((await account(req.headers.authorization)).wallet,progressInput.parse(req.body)));
 app.put('/me/equipment',async req=>service.equip((await account(req.headers.authorization)).wallet,z.object({sku}).strict().parse(req.body).sku));
 app.post('/me/unequip',async req=>service.unequip((await account(req.headers.authorization)).wallet,z.object({slot:z.enum(['outfit','trail','frame','rack'])}).strict().parse(req.body).slot));
 app.get('/weekly/leaderboard',async req=>ranked.weekly(req.headers.authorization?(await account(req.headers.authorization)).wallet:undefined));
 app.get('/league',async req=>league.summary(req.headers.authorization?(await account(req.headers.authorization)).wallet:undefined));
 app.post('/league/start',async req=>league.start((await account(req.headers.authorization)).wallet,z.object({contractId:z.string().max(32),rulesHash:z.string().regex(/^[a-f0-9]{64}$/),requestKey:uuid}).strict().parse(req.body)));
 app.post('/league/identity',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async req=>{const a=await account(req.headers.authorization),{domain}=z.object({domain:z.string().regex(/^[a-zA-Z0-9-]{1,63}\.skr$/)}).strict().parse(req.body);let owner;try{owner=await resolveSkr(domain);}catch{throw new ServiceError(503,'Name service unavailable. Your wallet address is still usable.');}if(owner!==a.wallet)throw new ServiceError(400,'This .skr name is not currently registered to your connected wallet.');await service.pool.query('INSERT INTO league_identity(wallet,domain) VALUES($1,$2) ON CONFLICT(wallet) DO UPDATE SET domain=$2,checked_at=now()',[a.wallet,domain.toLowerCase()]);return {domain:domain.toLowerCase()};});
 app.post('/league/equip',async req=>league.equip((await account(req.headers.authorization)).wallet));
 app.get('/daily',async()=>ranked.daily());
 const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{try{return new Date(`${v}T00:00:00Z`).toISOString().slice(0,10)===v;}catch{return false;}}),rulesHash=z.string().regex(/^[a-f0-9]{64}$/);
 app.get('/daily/:day/leaderboard',async req=>{const input=z.object({day}).parse(req.params),wallet=req.headers.authorization?(await account(req.headers.authorization)).wallet:undefined;return ranked.leaderboard(input.day,wallet);});
 app.get('/runs/current',async req=>ranked.current((await account(req.headers.authorization)).wallet));
 app.post('/runs',{config:{rateLimit:{max:12,timeWindow:'1 minute'}}},async req=>ranked.start((await account(req.headers.authorization)).wallet,z.object({day,rulesHash,requestKey:uuid}).strict().parse(req.body)));
 app.get('/runs/:id',async req=>ranked.get((await account(req.headers.authorization)).wallet,z.object({id:uuid}).parse(req.params).id));
 app.post('/runs/:id/abandon',async req=>ranked.abandon((await account(req.headers.authorization)).wallet,z.object({id:uuid}).parse(req.params).id));
 app.post('/runs/:id/finish',{bodyLimit:1024*1024,config:{rateLimit:{max:12,timeWindow:'1 minute'}}},async req=>ranked.submit((await account(req.headers.authorization)).wallet,z.object({id:uuid}).parse(req.params).id,z.object({rulesHash,replay:z.unknown()}).strict().parse(req.body)));
 app.get('/campaign',async req=>campaign.summary((await account(req.headers.authorization)).wallet));
 app.get('/campaign/leaderboard',async()=>campaign.leaderboard());
 app.post('/campaign/claim',async req=>{z.object({}).strict().parse(req.body);return campaign.claim((await account(req.headers.authorization)).wallet);});
 app.post('/campaign/runs',{bodyLimit:1024*1024,config:{rateLimit:{max:12,timeWindow:'1 minute'}}},async req=>{const a=await account(req.headers.authorization),b=z.object({mission:z.enum(CAMPAIGN_IDS as [MissionId,...MissionId[]]),rulesHash,replay:z.unknown()}).strict().parse(req.body);return campaign.submit(a.wallet,b.mission,b.rulesHash,b.replay);});
 app.get('/paid/challenge',async()=>paid.challenge());
 app.get('/paid/entries',async req=>paid.list((await account(req.headers.authorization)).wallet));
 app.post('/paid/entries',{config:{rateLimit:{max:12,timeWindow:'1 minute'}}},async req=>{const a=await account(req.headers.authorization),b=z.object({requestKey:uuid,termsVersion:z.literal('devnet-v1')}).strict().parse(req.body);return paid.quote(a.wallet,b.requestKey,b.termsVersion);});
 app.get('/paid/entries/:id',async req=>paid.get((await account(req.headers.authorization)).wallet,z.object({id:uuid}).parse(req.params).id));
 app.post('/paid/entries/:id/prepare',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params);z.object({}).strict().parse(req.body);return paid.prepare(a.wallet,id);});
 app.post('/paid/entries/:id/transaction',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params),body=z.object({signature:z.string().refine(v=>{try{validateSignature(v);return true;}catch{return false;}})}).strict().parse(req.body);return paid.attach(a.wallet,id,body.signature);});
 app.post('/paid/entries/:id/reconcile',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params);z.object({}).strict().parse(req.body);return paid.reconcile(a.wallet,id);});
 app.post('/paid/entries/:id/start',async req=>{const a=await account(req.headers.authorization),b=z.object({rulesHash,startKey:uuid}).strict().parse(req.body);return paid.start(a.wallet,z.object({id:uuid}).parse(req.params).id,b.rulesHash,b.startKey);});
 app.post('/paid/entries/:id/cancel',async req=>{const a=await account(req.headers.authorization),{id}=z.object({id:uuid}).parse(req.params);z.object({}).strict().parse(req.body);return paid.cancel(a.wallet,id);});
 app.post('/paid/entries/:id/finish',{bodyLimit:1024*1024,config:{rateLimit:{max:12,timeWindow:'1 minute'}}},async req=>paid.submit((await account(req.headers.authorization)).wallet,z.object({id:uuid}).parse(req.params).id,z.object({runId:uuid,rulesHash,replay:z.unknown()}).strict().parse(req.body)));
 return app;
}
