import {useEconomy} from '../commerce/EconomyProvider';
import React,{useState} from 'react';
import {Modal,Pressable,Text,View,useWindowDimensions} from 'react-native';
import {CREDIT_PACKS} from '../../shared/store';
import type {ProductId} from '../../shared/commerce';
import PaywallVideo from '../commerce/PaywallVideo';
export default function WalletPanel({visible,onClose,sku='campaign',onDemoComplete}:{visible:boolean;onClose:()=>void;checkout?:boolean;sku?:ProductId;fullScreen?:boolean;onDemoComplete?:(credits:number)=>Promise<void>}){
 const economy=useEconomy(),pack=CREDIT_PACKS.find(p=>p.id===sku),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(''),{height}=useWindowDimensions();
 async function pay(){if(busy||done)return;setBusy(true);try{if(!onDemoComplete)throw Error('Open checkout from Leaderboard or the credit store.');await onDemoComplete(pack?.credits??0);setDone(true);}catch(e){setError(e instanceof Error?e.message:'Try again.');}finally{setBusy(false);}}
 return <Modal visible={visible} animationType="fade" onRequestClose={onClose}><View style={{flex:1,backgroundColor:'#0C1012',alignItems:'center',padding:20}}><View style={{width:'100%',maxWidth:430,flex:1,gap:18}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><Pressable accessibilityRole="button" accessibilityLabel="Back from checkout" onPress={onClose} style={{padding:10}}><Text style={{fontSize:24,color:'#CFE6E4'}}>‹</Text></Pressable><Text style={{fontSize:10,color:'#9CBAAC',letterSpacing:1}}>DEMO · ◈ {economy.balance.toLocaleString()} CREDITS</Text></View><View style={{height:Math.min(height*.25,220),borderRadius:20,overflow:'hidden',backgroundColor:'#1C3529',alignItems:'center',justifyContent:'center'}}>{pack?<Text style={{fontSize:75,color:'#CFE6E4'}}>◈</Text>:<PaywallVideo active={visible}/>}</View><Text style={{fontSize:32,color:'#EDF5EE',fontWeight:'900'}}>{done?pack?'Demo credits added.':'You’re in.':pack?`${pack.credits.toLocaleString()} credits`:'Join the weekly climb.'}</Text><Text style={{fontSize:14,lineHeight:22,color:'#B7CFC1'}}>{pack?'This adds free test credits to this browser only. In the Android app, a credit pack opens Phantom for a real SOL or SKR payment.':'3 missions each week. 5 ranked chances on each. Your best complete runs decide your rank. No buying extra attempts.'}</Text>{!pack&&<Text style={{fontSize:13,color:'#D2E8DB'}}>Live pass: 500 SKR or $10 worth of SOL. Pay once. Existing pass owners keep access.</Text>}<View style={{flex:1}}/>{!!error&&<Text style={{color:'#E8C5AB'}}>{error}</Text>}<Pressable accessibilityRole="button" accessibilityLabel={done?'Done':pack?`Add ${pack.credits} demo credits`:'Unlock demo Game Pass'} disabled={busy} onPress={()=>done?onClose():void pay()} style={{minHeight:54,borderRadius:15,backgroundColor:'#CFE6E4',alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:14,fontWeight:'800',color:'#16362A'}}>{busy?'Saving…':done?'Done':pack?`Add ${pack.credits} demo credits`:'Try the Game Pass'}</Text></Pressable><Text style={{fontSize:11,lineHeight:17,color:'#8EA99A',textAlign:'center'}}>This browser preview does not transfer SOL or SKR. Android checkout uses Phantom approval.{!pack?' Weekly token prizes are not active.':''}</Text></View></View></Modal>;
}
