import {IS_MAINNET,SKR_LABEL,transactionLink} from '../wallet/config';
import React from 'react';
import {Linking,Modal,Pressable,ScrollView,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {CAMPAIGN_OFFER,campaignStats,type CampaignSummary,type CampaignRank} from '../../shared/economy';
export default function RewardsView({visible,onClose,local,summary,board,message,onClaim,onSync,busy,onLegacy}:{visible:boolean;onClose:()=>void;local:boolean;summary?:CampaignSummary;board:CampaignRank[];message:string;onClaim:()=>void;onSync:()=>void;busy:boolean;onLegacy?:()=>void}){
 const hasReward=(summary?.rebate??0)>0;
 const stats=campaignStats(summary?.runs??[]),{height}=useWindowDimensions(),compact=height<700,insets=useSafeAreaInsets();
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={[s.back,{paddingTop:15+insets.top,paddingBottom:15+insets.bottom}]}><View style={[s.sheet,{gap:compact?10:16,maxHeight:'94%'}]}><View style={s.row}><Text style={s.tag}>{local?'LOCAL SCORECARD':'VERIFIED CAMPAIGN'}</Text><Pressable accessibilityRole="button" accessibilityLabel="Close rewards" hitSlop={12} onPress={onClose} style={{minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'}}><Text style={s.close}>✕</Text></Pressable></View><ScrollView style={{flexGrow:0,flexShrink:1}} contentContainerStyle={{gap:compact?10:16}}><Text style={[s.title,compact&&{fontSize:21,lineHeight:24}]}>Make every escape count.</Text>
 <View style={s.card}><View style={s.row}><Text style={s.big}>{stats.cleared}<Text style={s.dim}> / 12</Text></Text>{hasReward&&<Text style={s.money}>{summary?.rebate??0} {local?'credits':SKR_LABEL} back</Text>}</View><View style={s.track}><View style={[s.fill,{width:`${stats.cleared/12*100}%`}]}/></View><Text style={s.body}>{!hasReward?'Keep the phones you recover. Every verified clear adds points to the leaderboard.':summary?.state==='settled'?'Completion rebate received. You can keep improving your rank.':summary?.state==='pending'||summary?.state==='queued'?'Rebate queued. Check status; do not pay again.':'Complete all 12 missions, then claim once. Retries are included. No extra entry fee.'}</Text></View>
 <View style={s.row}>{[[stats.score.toLocaleString(),'POINTS'],[(stats.ticks/30).toFixed(1)+'s','TOTAL TIME'],[stats.clean.toString(),'CLEAN WINS']].map(([value,label])=><View key={label}><Text style={s.stat}>{value}</Text><Text style={s.tag}>{label}</Text></View>)}</View>
 <Text style={s.body}>{compact?'Rank: total points → levels → time → clean wins → health. Exact ties share rank.':'Rank order: total points from your best verified run per level → levels cleared → time → clean wins → health. Exact ties share rank. Outfits add no advantage.'}</Text>
 <Text style={s.tag}>{local?'YOUR RESULTS · NOT A GLOBAL BOARD':'LEADERBOARD · TOP 3'}</Text>{board.slice(0,compact?1:3).map(r=><View key={r.wallet} style={s.row}><Text style={s.white}>#{r.rank} {local?'You':r.wallet.slice(0,4)+'…'+r.wallet.slice(-4)}</Text><Text style={s.body}>{r.score.toLocaleString()} pts · {r.cleared} levels · {(r.ticks/30).toFixed(1)}s</Text></View>)}{!board.length&&<Text style={s.body}>No verified scores yet.</Text>}
 {!!message&&<Text accessibilityLiveRegion="polite" style={s.notice}>{message}</Text>}
 {hasReward&&<Pressable accessibilityRole="button" accessibilityLabel="Claim completion rebate" disabled={busy||summary?.state!=='ready'} onPress={onClaim} style={[s.button,(busy||summary?.state!=='ready')&&{opacity:.4}]}><Text style={s.buttonText}>{summary?.state==='settled'?'REBATE RECEIVED':`CLAIM ${summary?.rebate??CAMPAIGN_OFFER.rebate} ${local?'CREDITS':SKR_LABEL}`}</Text></Pressable>}
 {!local&&<Pressable accessibilityRole="button" accessibilityLabel="Sync campaign rewards" disabled={busy} onPress={onSync}><Text style={s.link}>{busy?'SYNCING…':hasReward?'SYNC REPLAYS / CHECK PAYOUT':'SYNC RESULTS'}</Text></Pressable>}
 {!!summary?.signature&&<Pressable accessibilityRole="link" onPress={()=>void Linking.openURL(transactionLink(summary.signature!))}><Text style={s.link}>VIEW FINALIZED RECEIPT ↗</Text></Pressable>}{!!onLegacy&&!IS_MAINNET&&<Pressable accessibilityRole="button" accessibilityLabel="Previous entry receipts" onPress={onLegacy}><Text style={s.link}>PREVIOUS ENTRY RECEIPTS / RESUME</Text></Pressable>}<Text numberOfLines={compact?2:undefined} style={s.fine}>{local?'Test credits stay in this browser. No withdrawals.':IS_MAINNET?hasReward?'Your earlier purchase includes a reserved SKR reward.':'Weekly standings are separate from campaign progress.':'Devnet only. Replays are checked by the server. Payments and payouts use the treasury wallet. Board ranks the current rules version.'}</Text>
 </ScrollView></View></View></Modal>;
}
const s=StyleSheet.create({back:{flex:1,backgroundColor:'#000A',alignItems:'center',justifyContent:'center',padding:15},sheet:{width:'100%',maxWidth:440,padding:20,borderRadius:24,borderWidth:1,borderColor:'#3E6265',backgroundColor:'#101D23'},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},tag:{color:'#91C4B6',fontSize:9,letterSpacing:1,fontWeight:'800'},close:{color:'#CFE8E0',fontSize:20,padding:6},title:{color:'#F1F9E9',fontSize:25,lineHeight:29,fontWeight:'900'},card:{backgroundColor:'#1B3439',padding:15,borderRadius:15,gap:10},big:{fontSize:32,fontWeight:'900',color:'#DDFEE8'},dim:{fontSize:16,color:'#8BABAC'},money:{color:'#C6F3DA',fontSize:13,fontWeight:'800'},track:{height:5,backgroundColor:'#344F57',borderRadius:5},fill:{height:5,backgroundColor:'#BEF3D9',borderRadius:5},body:{color:'#A7BDC5',fontSize:11,lineHeight:17},stat:{fontSize:20,fontWeight:'800',color:'#E7F0E8'},white:{color:'#DEEFDF',fontSize:12},notice:{color:'#FAD9B2',fontSize:11,lineHeight:16},button:{backgroundColor:'#C4F7DC',padding:16,borderRadius:12},buttonText:{color:'#17352E',fontSize:12,fontWeight:'900',textAlign:'center'},link:{textAlign:'center',color:'#C4EAD9',fontSize:11,padding:5},fine:{color:'#829AA5',fontSize:9,lineHeight:13}});
