import React,{useState} from 'react';
import {Modal,Pressable,ScrollView,Text,View} from 'react-native';
import {useAccount} from '../commerce/account-context';
import {PRODUCTS} from '../../shared/commerce';
import {CAMPAIGN_IDS,getLevel,type MissionId} from '../game/level';
import {unlocked,type Progress} from '../progress/model';
export default function Hideout({visible,onClose,onStart,onShop,onSync,onDaily,onPaid,onSettings,progress,syncStatus}:{visible:boolean;onClose:()=>void;onStart:(id:MissionId)=>void;onShop:()=>void;onSync:()=>void;onDaily:()=>void;onPaid:()=>void;onSettings:()=>void;progress:Progress;syncStatus:string}){
 const {account,preview}=useAccount(),equipment=account?.equipment??{},framed=equipment.frame==='profile-frame',themed=equipment.rack==='rack-theme',completed=Object.keys(progress.missions).length;
 const next=CAMPAIGN_IDS.find(id=>!progress.missions[id])??CAMPAIGN_IDS[11]!,[selected,setSelected]=useState<MissionId>('practice'),level=getLevel(selected),available=unlocked(progress,selected);
 const button=(text:string,onPress:()=>void,subtle=false)=><Pressable accessibilityRole="button" accessibilityLabel={text} onPress={onPress} style={{padding:15,borderRadius:12,backgroundColor:subtle?'#263c33':'#cfe6e4',flexGrow:1}}><Text style={{color:subtle?'#d8e8df':'#19362c',fontWeight:'700',textAlign:'center',fontSize:12}}>{text}</Text></Pressable>;
 return <Modal visible={visible} transparent animationType="none" onRequestClose={onClose}><View style={{flex:1,backgroundColor:'#081510fa',padding:18,justifyContent:'center',alignItems:'center'}}><ScrollView style={{width:'100%',maxWidth:900,flexGrow:0,maxHeight:'96%',borderRadius:24,backgroundColor:'#142720',borderWidth:1,borderColor:'#385547'}} contentContainerStyle={{padding:26,gap:20}}>
 <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10}}><Text style={{color:'#a8ecd7',fontSize:10,letterSpacing:2}}>STEAL A SEEKER / HIDEOUT</Text><View style={{width:125}}>{button('Back to game',onClose,true)}</View></View><Text style={{color:'#edf2e3',fontSize:38,fontWeight:'800',letterSpacing:-1}}>Your next bad idea.</Text><Text style={{color:'#a7c2b1',fontSize:14,lineHeight:23}}>{completed===12?'Twelve phones recovered. Try for three stars on every route.':'Pick a route, check the patrols, get the phone home.'}</Text>
 <View style={{padding:20,borderRadius:18,borderWidth:framed?3:1,borderColor:framed?'#c8eedb':'#3e6054',backgroundColor:'#213c2e',gap:13}}><Text style={{color:'#e2f2e8',fontSize:21,fontWeight:'700'}}>{PRODUCTS.find(p=>p.id===equipment.outfit)?.name??'Original Courier'}</Text><Text style={{color:'#d1e4d8'}}>{completed} / 12 missions · {Object.values(progress.missions).reduce((n,b)=>n+(b?.stars??0),0)} stars</Text>{button(`Continue · ${getLevel(next).title}`,()=>onStart(next))}</View>
 <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{button('Shop / equip owned items',onShop,true)}{button('Daily challenge / leaderboard',onDaily,true)}{button(preview?'Entry challenge · local credits':'Paid devnet challenge',onPaid,true)}{button('Settings / controls',onSettings,true)}</View>
 <Text style={{color:'#e1edde',fontSize:24,fontWeight:'700'}}>The twelve heists</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{CAMPAIGN_IDS.map(id=>{const l=getLevel(id),best=progress.missions[id],open=unlocked(progress,id);return <Pressable key={id} accessibilityRole="button" accessibilityLabel={`Mission ${l.number}: ${l.title}${open?'':'. Locked'}`} accessibilityState={{selected:selected===id}} onPress={()=>setSelected(id)} style={{width:'30%',minWidth:140,flexGrow:1,padding:15,gap:9,borderRadius:15,backgroundColor:selected===id?'#365441':l.number<=4?'#233b2c':l.number<=8?'#223a40':'#3b3627',borderWidth:1,borderColor:selected===id?'#bbd9a8':'#405347',opacity:open?1:.55}}><Text style={{color:'#96bfa7',fontSize:10,letterSpacing:1}}>{String(l.number).padStart(2,'0')} / {l.number<=4?'WAREHOUSE':l.number<=8?'ROOFTOPS':'VAULT'}</Text><Text style={{color:'#e8efdd',fontSize:15,fontWeight:'700'}}>{l.title}</Text><Text style={{color:'#bed8ae',fontSize:11}}>{best?'★'.repeat(best.stars)+'☆'.repeat(3-best.stars):open?'READY':'LOCKED'}</Text>{best&&<Text style={{color:'#afc1b4',fontSize:10}}>Best {best.seconds.toFixed(1)}s · {best.completions} completed</Text>}</Pressable>;})}</View>
 <View style={{padding:20,gap:12,borderRadius:16,backgroundColor:'#0d1c16'}}><Text style={{color:'#e5eddc',fontSize:22,fontWeight:'700'}}>{level.title}</Text><Text style={{color:'#aec5b4',lineHeight:22,fontSize:13}}>{level.briefing}</Text><Text style={{color:'#91b29c',fontSize:12}}>Goal: {level.targetSeconds}s · limit {level.hardLimitSeconds/60} min · {level.patrols.length} guards</Text><Pressable accessibilityRole="button" accessibilityLabel={`Start ${level.title}`} disabled={!available} onPress={()=>onStart(selected)} style={{padding:15,borderRadius:12,backgroundColor:available?'#cfe6e4':'#354139'}}><Text style={{color:available?'#173b28':'#91a397',fontWeight:'700',textAlign:'center'}}>{available?'START HEIST ↗':'FINISH THE PREVIOUS HEIST'}</Text></Pressable></View>
 <Text style={{color:'#dcece2',fontSize:22,fontWeight:'700'}}>Your collection</Text><View style={{backgroundColor:themed?'#324d4b':'#101c19',borderColor:themed?'#c5dfe0':'#3a5248',borderWidth:themed?3:1,padding:14,borderRadius:15,flexDirection:'row',flexWrap:'wrap',gap:12}}>{CAMPAIGN_IDS.map(id=>{const won=!!progress.missions[id],l=getLevel(id);return <View key={id} accessibilityLabel={`${l.title}: ${won?'recovered':'not recovered'}`} style={{minWidth:44,flex:1,alignItems:'center',gap:8}}><View style={{width:24,height:41,borderWidth:2,borderRadius:5,borderColor:won?'#eceddf':'#46574f',backgroundColor:won?'#a8dcc8':'#1f2d27'}}/><Text style={{color:won?'#d8eadd':'#72877b',fontSize:10}}>{String(l.number).padStart(2,'0')}</Text></View>;})}</View><Text style={{color:'#849d8e',fontSize:11}}>Fictional game collectibles. No physical phone rewards.{preview?' Local browser playtest. Purchases and records stay in this browser.':''}</Text>{!!syncStatus&&<Text style={{color:'#acc9b7',fontSize:12}}>{syncStatus}</Text>}{!preview&&button('Sync progress',onSync)}
 </ScrollView></View></Modal>;
}
