import {IS_MAINNET} from '../wallet/config';
import {environmentFor} from '../game/environment';
import React,{useEffect,useState} from 'react';
import {Image,Modal,Pressable,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {useAccount} from '../commerce/account-context';
import {CAMPAIGN_IDS,getLevel,type MissionId} from '../game/level';
import {PHONE_EDITIONS,editionIndex,phoneEdition} from '../game/collection';
import {unlocked,type Progress} from '../progress/model';
import CourierArt from './CourierArt';
import BottomTabs from './BottomTabs';
import WeeklyBoard,{WeeklyCard,useWeekly} from '../ranked/WeeklyBoard';
import PhoneInspector from './PhoneInspector';
import PhoneArt from './PhoneArt';import MissionPreview from './MissionPreview';import HideoutBalance from './HideoutBalance';
const districts=[{name:'WAREHOUSE',art:require('../../assets/world-v3/district-warehouse.png')},{name:'ROOFTOPS',art:require('../../assets/world-v3/district-rooftops.png')},{name:'POWERWORKS / VAULT',art:require('../../assets/world-v3/district-powerworks.png')}];
type Props={onContractStart:(ticket:import('../../shared/ranked').RunTicket)=>void;initialTab?:'map'|'leaderboard';visible:boolean;onClose:()=>void;onStart:(id:MissionId)=>void;onShop:()=>void;onSync:()=>void;onDaily:()=>void;onPaid:()=>void;onSettings:()=>void;progress:Progress;syncStatus:string};
export default function Hideout({onContractStart,initialTab='map',visible,onClose,onStart,onShop,onSync,onDaily,onPaid,onSettings,progress,syncStatus}:Props){
 const judge=process.env.EXPO_PUBLIC_JUDGE_PREVIEW==='1';
 const {account,preview}=useAccount(),equipment=account?.equipment??{},themed=equipment.rack==='rack-theme',framed=equipment.frame==='profile-frame';
 const {width,height}=useWindowDimensions(),insets=useSafeAreaInsets(),usable=height-insets.top-insets.bottom,w=Math.min(width-24,430),roomH=Math.max(150,Math.min(500,usable-400)),roomW=Math.min(w,roomH*2/3);
 const completed=CAMPAIGN_IDS.filter(id=>!!progress.missions[id]).length,next=CAMPAIGN_IDS.find(id=>!progress.missions[id])??CAMPAIGN_IDS[11]!;
 const [weeklyDetail,setWeeklyDetail]=useState(false);
 const [inspection,setInspection]=useState<number|null>(null);
 const rackPhoneHeight=Math.max(12,Math.min(68,((roomW*.59-18)/4-8)*388/212,((roomH*.48-18)*.88/3-8)));
 const weekly=useWeekly(visible);
 const [tab,setTab]=useState<'rack'|'map'|'leaderboard'|'briefing'|'complete'>(initialTab),[selected,setSelected]=useState<MissionId>('practice');
 useEffect(()=>{if(visible){setSelected(next);setInspection(null);}},[visible,completed]);
 const level=getLevel(selected),edition=phoneEdition(selected),best=progress.missions[selected],available=unlocked(progress,selected),mapH=Math.max(78,Math.min(175,(usable-395)/3)),nodeY=usable<760?[0,0,0,0]:[22,4,22,4];
 const action=(label:string,name:string,onPress:()=>void,primary=false,disabled=false,fluid=false)=><Pressable accessibilityRole="button" accessibilityLabel={name} onPress={onPress} disabled={disabled} style={[s.button,fluid&&{flexGrow:1,flexBasis:0,minWidth:0},primary&&s.primary,disabled&&{opacity:.4}]}><Text style={[s.buttonText,primary&&{color:'#173739'}]}>{label}</Text></Pressable>;
 return <Modal visible={visible} transparent animationType="none" onRequestClose={onClose}><View style={[s.overlay,{paddingTop:insets.top+8,paddingBottom:insets.bottom+8}]}><View style={{width:w,flex:1,maxHeight:980}}>
 {!(tab==='leaderboard'&&weeklyDetail)&&<><View style={s.header}><View style={{flexDirection:'row',alignItems:'center',gap:8}}><Image source={require('../../assets/messages/pause.png')} style={{width:40,height:40,borderRadius:20,borderWidth:framed?2:0,borderColor:'#CFE6E4'}}/><View><Text style={s.brand}>STEAL A SEEKER</Text><Text style={s.small}>{completed} / 12 missions · {Object.values(progress.missions).reduce((n,b)=>n+(b?.stars??0),0)} stars</Text></View></View><View style={{alignItems:'flex-end',gap:5}}>{tab==='rack'?<HideoutBalance/>:preview?<Text style={s.small}>BROWSER DEMO</Text>:<HideoutBalance/>}{judge&&<Text style={s.small}>JUDGE · OFFLINE</Text>}<Pressable accessibilityRole="button" accessibilityLabel="Settings" onPress={onSettings} style={{minHeight:28,justifyContent:'center'}}><Text style={s.small}>Settings ⚙</Text></Pressable></View></View>
 <View style={s.navigation}>
  <View><Text accessibilityRole="header" style={s.screenTitle}>{tab==='rack'?'Hideout':tab==='briefing'?'Mission briefing':tab==='complete'?'Collection complete':tab==='leaderboard'?'Leaderboard':'Missions'}</Text><Text style={s.small}>{tab==='rack'?'Your collection and courier.':tab==='leaderboard'?'New missions every Monday.':'Choose your next heist.'}</Text></View>

 </View>
 </>}
 {tab==='leaderboard'?<WeeklyBoard onDetailChange={setWeeklyDetail} showStandings={initialTab==='leaderboard'} state={weekly} onStart={onContractStart}/>:tab==='complete'?<View testID="campaign-complete" style={{flex:1,justifyContent:'center',alignItems:'center',gap:16}}><Image source={require('../../assets/messages/success.png')} style={{width:Math.min(w*.7,210),height:Math.min(w*.7,210),borderRadius:24}}/><Text style={[s.title,{fontSize:28,textAlign:'center'}]}>Twelve phones. One courier.</Text><Text style={[s.small,{textAlign:'center'}]}>You cleared every heist across all three districts.{'\n'}{Object.values(progress.missions).reduce((n,b)=>n+(b?.stars??0),0)} / 36 stars earned. Your collection stays here.</Text>{action('VIEW YOUR COLLECTION ↗','View completed collection',()=>setTab('rack'),true)}{action('CLIMB THE WEEKLY BOARD','Open weekly leaderboard after campaign',()=>setTab('leaderboard'))}{action('IMPROVE YOUR STARS','Replay completed missions',()=>setTab('map'))}</View>:tab==='rack'?<View style={{flex:1,justifyContent:'center',gap:8}}>
 <View testID="hideout-room" style={{width:roomW,height:roomH,alignSelf:'center',borderRadius:18,overflow:'hidden',borderWidth:1,borderColor:'#343F44'}}><Image source={require('../../assets/world-v3/hideout.png')} style={[StyleSheet.absoluteFill,{width:"100%",height:"100%"}]} resizeMode="stretch"/>
 <View style={{position:'absolute',left:'9%',bottom:'25%'}}><CourierArt height={roomW*.25} outfit={equipment.outfit}/></View>
 <View testID="charging-rack" style={[s.rack,{left:'28%',top:'34%',width:'59%',height:'48%',borderColor:themed?'#AFE8D6':'#65797B',backgroundColor:themed?'#224340':'#232D33'}]}><View style={{flexDirection:'row',flexWrap:'wrap',height:'88%'}}>{CAMPAIGN_IDS.map((id,i)=>{const won=!!progress.missions[id];return <Pressable key={id} accessibilityRole="button" accessibilityLabel={`Collection ${PHONE_EDITIONS[i]!.name}: ${won?'recovered':'not recovered'}`} accessibilityState={{selected:selected===id}} onPress={()=>{setSelected(id);setInspection(i);}} style={{width:'25%',height:'33.333%',padding:3}}><View style={[s.slot,{borderColor:selected===id?'#E8FFF4':won?'#75CDBA':'#455059',backgroundColor:won?'#193D3A':'#10151B'}]}>{won?<PhoneArt index={i} height={rackPhoneHeight}/>:<View style={{width:15,height:27,borderRadius:4,borderWidth:1,borderStyle:'dashed',borderColor:'#637279'}}/>}</View></Pressable>})}</View><Text style={[s.small,{textAlign:'center',fontSize:7,letterSpacing:1,marginTop:4}]}>{completed} / 12</Text></View>
 </View>
 <Pressable accessibilityRole="button" accessibilityLabel={`Inspect ${edition.name} in 3D`} onPress={()=>setInspection(editionIndex(selected))} testID="collection-detail" style={s.collectionDetail}><PhoneArt index={editionIndex(selected)} height={58}/><View style={{flex:1,gap:4}}><Text style={s.title}>{edition.name}</Text><Text style={s.small}>{best?'RECOVERED':'VIRTUAL PHONE'} · {String(level.number).padStart(2,'0')} {level.title}</Text></View><Text style={{color:'#CFE6E4',fontSize:15}}>{best?'★'.repeat(best.stars):'◇'} ↗</Text></Pressable>
 <View style={{flexDirection:'row',gap:8}}>{action('Wardrobe','Shop / equip owned items',onShop,true,false,true)}{action('Rewards','Campaign rewards',onPaid,false,false,true)}</View>

 <Text style={[s.small,{fontSize:9,textAlign:'center'}]}>Virtual phone collection · {preview?'demo credits · no cash value':IS_MAINNET?'mainnet · real money':'devnet test build'}</Text>
 </View>:tab==='map'?<View style={{flex:1,justifyContent:'center'}}><WeeklyCard state={weekly} onPress={()=>setTab('leaderboard')}/>{districts.map((d,di)=><View key={d.name} testID={`district-${di}`} style={{height:mapH}}><Text style={s.districtTitle}>{d.name}</Text><View style={{flex:1,overflow:'hidden',borderRadius:8}}><Image source={d.art} style={[StyleSheet.absoluteFill,{width:"100%",height:"100%"}]} resizeMode="cover"/>{[0,1,2].map(j=>{const xs=[8,31,56,79],ys=nodeY,dx=(xs[j+1]!-xs[j]!)*w/100,dy=(ys[j+1]!-ys[j]!)*(mapH-20)/100,len=Math.hypot(dx,dy);return <View key={j} pointerEvents="none" style={{position:'absolute',left:xs[j]!*w/100+21.5+(dx-len)/2,top:ys[j]!*(mapH-20)/100+21.5+dy/2,width:len,height:2,backgroundColor:'#A2D6C8',opacity:.6,transform:[{rotate:`${Math.atan2(dy,dx)}rad`}]}}/>;})}{CAMPAIGN_IDS.slice(di*4,di*4+4).map((id,j)=>{const l=getLevel(id),open=unlocked(progress,id),won=progress.missions[id];return <Pressable key={id} accessibilityRole="button" accessibilityLabel={`Mission ${l.number}: ${l.title}${open?'':'. Locked'}`} onPress={()=>{setSelected(id);setTab('briefing');}} style={[s.node,{left:`${[8,31,56,79][j]!}%`,top:`${nodeY[j]!}%`,borderColor:open?'#CFE6E4':'#54616B',backgroundColor:open?'#284C4C':'#1D252D',opacity:open?1:.65}]}><Text style={{color:open?'#EEFFF6':'#87959F',fontWeight:'800',fontSize:14}}>{String(l.number).padStart(2,'0')}</Text><Text style={{color:'#CFE6E4',fontSize:7,position:'absolute',bottom:-15}}>{won?'★'.repeat(won.stars):open?'READY':'LOCKED'}</Text></Pressable>})}</View></View>)}<View style={{marginTop:8}}>{completed===12?action('COLLECTION COMPLETE ↗','View campaign ending',()=>setTab('complete'),true):action(`CONTINUE · ${getLevel(next).title.toUpperCase()} ↗`,`Continue · ${getLevel(next).title}`,()=>onStart(next),true)}</View></View>:<View style={{flex:1,justifyContent:'center',gap:10}}>
 <View style={{flexDirection:'row',gap:10,alignItems:'center'}}><Pressable accessibilityRole="button" accessibilityLabel="Back to district map" onPress={()=>setTab('map')} style={{padding:10}}><Text style={{color:'#CFE6E4',fontSize:22}}>‹</Text></Pressable><View style={{flex:1}}><Text style={s.eyebrow}>{environmentFor(level).place.toUpperCase()} · {String(level.number).padStart(2,'0')}</Text><Text style={[s.title,{fontSize:24}]}>{level.title}</Text></View></View>
 <View testID="mission-preview" style={{alignSelf:'center',borderRadius:14,overflow:'hidden',borderWidth:1,borderColor:'#445259'}}><MissionPreview mission={selected} size={Math.max(100,Math.min(w-30,(usable-380)*.6,250))}/></View>
 <Pressable accessibilityRole="button" accessibilityLabel={`Inspect ${edition.name} in 3D`} onPress={()=>setInspection(editionIndex(selected))} style={s.collectionDetail}><PhoneArt index={editionIndex(selected)} height={64}/><View style={{flex:1,gap:6}}><Text style={s.title}>Recover {edition.name}</Text><Text style={s.small}>{level.patrols.length} guard{level.patrols.length===1?'':'s'} · {level.decoys} decoys · {level.targets?.length??1} phone{(level.targets?.length??1)>1?'s':''}</Text><Text style={s.small}>{environmentFor(level).hook}</Text></View></Pressable>
 {action(available?'PLAY HEIST ↗':'FINISH THE PREVIOUS HEIST',`Start ${level.title}`,()=>onStart(selected),true,!available)}
 </View>}
 {tab==='rack'&&!!syncStatus&&<Pressable accessibilityRole="button" accessibilityLabel="Sync progress" onPress={onSync}><Text numberOfLines={1} style={s.small}>{syncStatus} · Retry sync ↻</Text></Pressable>}
 <BottomTabs selected={tab==='leaderboard'?'leaderboard':tab==='rack'||tab==='complete'?'rack':'map'} onChange={nextTab=>{if(nextTab!==tab){setWeeklyDetail(false);setTab(nextTab);}}}/>

 </View>{inspection!==null&&<PhoneInspector index={inspection} recovered={!!progress.missions[CAMPAIGN_IDS[inspection]!]} onClose={()=>setInspection(null)}/>}</View></Modal>;
}
const s=StyleSheet.create({overlay:{flex:1,backgroundColor:'#0C0C0E',alignItems:'center',paddingHorizontal:12},header:{height:50,flexShrink:0,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{fontSize:13,fontWeight:'800',color:'#F6F6F5',letterSpacing:.8},small:{fontSize:10,lineHeight:15,color:'#A7BCC1'},navigation:{flexShrink:0,minHeight:46,flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginVertical:6},screenTitle:{fontSize:27,lineHeight:32,fontWeight:'800',color:'#F1F6EF'},button:{flexGrow:0,minHeight:42,paddingHorizontal:10,paddingVertical:11,backgroundColor:'#202B32',borderRadius:12,alignItems:'center',justifyContent:'center'},primary:{backgroundColor:'#CFE6E4'},buttonText:{fontSize:10,fontWeight:'800',color:'#CFE6E4',textAlign:'center',letterSpacing:.2},rack:{position:'absolute',borderRadius:13,borderWidth:3,padding:6,shadowColor:'#000',shadowOffset:{width:0,height:7},shadowOpacity:.8,shadowRadius:4},slot:{flex:1,borderWidth:1,borderRadius:6,alignItems:'center',justifyContent:'center',overflow:'hidden'},title:{fontSize:18,fontWeight:'800',color:'#F1F6EF'},collectionDetail:{flexDirection:'row',gap:12,alignItems:'center',backgroundColor:'#141C22',borderWidth:1,borderColor:'#334149',borderRadius:14,paddingHorizontal:14,paddingVertical:5},shortcuts:{height:44,flexShrink:0,flexDirection:'row',gap:6},eyebrow:{fontSize:9,fontWeight:'700',letterSpacing:1.5,color:'#AECFC8'},districtTitle:{color:'#DCECE4',fontSize:11,letterSpacing:1.7,fontWeight:'700',height:20},node:{position:'absolute',width:43,height:43,borderRadius:24,borderWidth:3,alignItems:'center',justifyContent:'center',shadowColor:'#93E2D5',shadowRadius:7,shadowOpacity:.3,shadowOffset:{width:0,height:0}}});
