import React,{useState} from 'react';
import {Image,Pressable,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {useEconomy} from '../commerce/EconomyProvider';
import {STORE_ITEMS,type StoreItemId} from '../../shared/store';
import {CAMPAIGN_IDS} from '../game/level';
import {PHONE_EDITIONS} from '../game/collection';
import type {Progress} from '../progress/model';
import CourierArt from './CourierArt';
import PhoneArt from './PhoneArt';
const nightStage=require('../../assets/hideout-v3/night-stage.webp'),signalStage=require('../../assets/hideout-v3/signal-stage.webp');
const hero=require('../../assets/hideout-v3/classic.webp'),night=require('../../assets/hideout-v3/night.webp'),signal=require('../../assets/hideout-v3/signal.webp');
export default function HideoutStore({progress,onInspect}:{progress:Progress;onInspect:(i:number)=>void}){
 const e=useEconomy(),{height}=useWindowDimensions(),compact=height<720,[section,setSection]=useState<'outfits'|'gear'|'collection'>('outfits'),[selected,setSelected]=useState<StoreItemId>('night-courier'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[previewing,setPreviewing]=useState(false);
 const item=STORE_ITEMS.find(i=>i.id===selected)!,owned=e.owned.includes(item.id),equipped=e.equipment[item.kind]===item.id;
 const shownOutfit=section==='outfits'&&previewing?item.id:e.equipment.outfit;
 const items=STORE_ITEMS.filter(i=>section==='outfits'?i.kind==='outfit':i.kind!=='outfit');
 async function act(){if(busy)return;if(!owned&&e.balance<item.price){e.openCredits();return;}setBusy(true);setMessage('');try{await (equipped?e.unequip(item.kind):owned?e.equip(item.id):e.redeem(item.id));setPreviewing(false);setMessage(equipped?'Classic finish restored.':`${item.name} equipped.`);}catch(err){setMessage(err instanceof Error?err.message:'Try again.');}finally{setBusy(false);}}
 return <View testID="hideout-store" style={{flex:1,minHeight:0,gap:compact?7:10}}>
 <View style={{flex:1,minHeight:compact?105:160,maxHeight:360,borderRadius:16,overflow:'hidden',borderWidth:1,borderColor:e.equipment.rack==='rack-theme'?'#B4F0D5':'#365047',backgroundColor:'#182821'}}>
 <Image source={shownOutfit==='night-courier'?nightStage:shownOutfit==='signal-runner'?signalStage:hero} resizeMode="cover" style={[StyleSheet.absoluteFill,{width:'100%',height:'100%'}]}/>
 <View style={{position:'absolute',bottom:0,left:0,right:0,padding:10,backgroundColor:'#091411CE',flexDirection:'row',alignItems:'center',gap:10}}><View style={{borderWidth:e.equipment.frame==='profile-frame'?2:0,borderColor:'#BAE5D4',borderRadius:12,padding:2}}><CourierArt height={34} outfit={shownOutfit}/></View><View><Text style={s.eyebrow}>{shownOutfit===e.equipment.outfit?'EQUIPPED COURIER':'OUTFIT PREVIEW'}</Text><Text style={s.title}>{STORE_ITEMS.find(i=>i.id===shownOutfit)?.name??(shownOutfit==='ghost-courier'?'Ghost Courier':'Classic Courier')}</Text></View></View>
 </View>
 <View style={{flexDirection:'row',borderBottomWidth:1,borderColor:'#34483E'}}>{(['outfits','gear','collection'] as const).map(tab=><Pressable key={tab} accessibilityRole="tab" aria-selected={section===tab} accessibilityState={{selected:section===tab}} onPress={()=>{setSection(tab);setPreviewing(false);setSelected(tab==='outfits'?'night-courier':'escape-trail');setMessage('');}} style={{flex:1,minHeight:42,alignItems:'center',justifyContent:'center',borderBottomWidth:3,borderColor:section===tab?'#CFE6E4':'transparent'}}><Text style={{color:section===tab?'#D7ECE1':'#819F90',fontSize:12,fontWeight:'800'}}>{{outfits:'Outfits',gear:'Gear',collection:'Collection'}[tab]}</Text></Pressable>)}</View>
 {section==='collection'?<><View style={{flexDirection:'row',flexWrap:'wrap',gap:6}}>{CAMPAIGN_IDS.map((id,i)=>{const won=!!progress.missions[id];return <Pressable key={id} accessibilityRole="button" accessibilityLabel={`View ${PHONE_EDITIONS[i]!.name}, ${won?'recovered':'locked'}`} onPress={()=>onInspect(i)} style={{width:'23.5%',height:compact?53:68,borderWidth:1,borderColor:won?'#538875':'#2B4037',borderRadius:10,backgroundColor:'#17271F',alignItems:'center',justifyContent:'center'}}>{won?<PhoneArt index={i} height={compact?31:44}/>:<Text style={{fontSize:20,color:'#546F62'}}>◇</Text>}<Text numberOfLines={1} style={{fontSize:8,color:won?'#C7E2D4':'#779184',marginTop:2}}>{PHONE_EDITIONS[i]!.name}</Text></Pressable>;})}</View><Text style={s.note}>{CAMPAIGN_IDS.filter(id=>progress.missions[id]).length}/12 recovered · tap a phone to inspect</Text></>:<>
 <View style={{flexDirection:'row',gap:8}}>{items.map(p=><Pressable key={p.id} accessibilityRole="button" accessibilityState={{selected:p.id===selected}} accessibilityLabel={`Preview ${p.name}, ${p.price} credits`} onPress={()=>{setSelected(p.id);setPreviewing(true);setMessage('');}} style={{flex:1,minWidth:0,borderWidth:1,borderColor:p.id===selected?'#B7DFCD':'#345044',borderRadius:13,overflow:'hidden',backgroundColor:p.id===selected?'#203F31':'#13261C'}}>{p.kind==='outfit'?<Image source={p.id==='night-courier'?night:signal} resizeMode="contain" style={{width:'100%',height:compact?70:100}}/>:<View style={{height:compact?62:90,alignItems:'center',justifyContent:'center'}}><Text style={{color:'#B2DDC8',fontSize:35}}>{p.kind==='trail'?'↗':p.kind==='frame'?'▣':'▤'}</Text></View>}<View style={{padding:8,gap:4}}><Text numberOfLines={1} style={{color:'#E0EEE4',fontSize:10,fontWeight:'800'}}>{p.name}</Text><Text style={{color:'#9DCCB3',fontSize:10}}>{e.owned.includes(p.id)?e.equipment[p.kind]===p.id?'Equipped':'Owned':`◈ ${p.price}`}</Text></View></Pressable>)}</View>
 <View style={{gap:7}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View style={{flex:1}}><Text style={s.title}>{item.name}</Text><Text style={s.note}>{item.description}</Text></View>{item.kind==='outfit'&&<CourierArt height={38} outfit={item.id}/>}</View><Pressable accessibilityRole="button" accessibilityLabel={equipped?`Remove ${item.name}`:owned?`Equip ${item.name}`:e.balance<item.price?'Get more credits':`Unlock ${item.name} for ${item.price} credits`} disabled={busy||!e.ready} onPress={()=>void act()} style={{minHeight:45,borderRadius:12,backgroundColor:equipped?'#233D2E':'#CFE6E4',alignItems:'center',justifyContent:'center',opacity:busy?.5:1}}><Text style={{fontWeight:'800',fontSize:12,color:equipped?'#B8DCC9':'#153A2B'}}>{busy?'Saving…':equipped?item.kind==='outfit'?'Wear Classic':'Remove':owned?'Equip':e.balance<item.price?`Get ${item.price-e.balance} more credits`:`Unlock · ◈ ${item.price}`}</Text></Pressable></View>
 </>}
 <Text accessibilityLiveRegion="polite" numberOfLines={2} style={s.note}>{message||e.notice||(e.local?'Saved on this device · earn up to 150 credits per mission':'Wallet inventory · cosmetics never change weekly stats')}</Text>
 </View>;
}
const s=StyleSheet.create({eyebrow:{color:'#9EBDAD',fontSize:8,fontWeight:'700',letterSpacing:1.4},title:{fontSize:16,fontWeight:'800',color:'#EDF4EB'},note:{fontSize:10,lineHeight:15,color:'#96B5A2'}});
