import React,{useState} from 'react';
import {Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {CAMPAIGN_IDS,getLevel,type MissionId} from '../game/level';
import {unlocked,type Progress} from '../progress/model';
export default function MissionMap({visible,progress,current,onClose,onStart}:{visible:boolean;progress:Progress;current:MissionId;onClose:()=>void;onStart:(id:MissionId)=>void}){
 const [selected,setSelected]=useState<MissionId>('practice');const level=getLevel(selected),canPlay=unlocked(progress,selected);
 return <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose} onShow={()=>setSelected(current==='night-shift'?'practice':current)}><View style={s.backdrop}><ScrollView style={s.card} contentContainerStyle={{padding:22,gap:14}}>
  <Text style={s.eyebrow}>MISSION MAP</Text><Text style={s.title}>Choose your route.</Text><Text style={s.body}>Recover the phone and reach the exit. Each successful heist opens the next mission. Retry as often as you like.</Text>
  {CAMPAIGN_IDS.map(id=>{const l=getLevel(id),best=progress.missions[id],available=unlocked(progress,id);return <View key={id} style={{gap:10}}>{l.number%4===1&&<Text style={s.eyebrow}>{l.number<=4?'01 · THE WAREHOUSE':'02 · THE ROOFTOPS'}</Text>}<Pressable accessibilityRole="button" accessibilityLabel={`Mission ${l.number}: ${l.title}${available?'':'. Locked'}`} accessibilityState={{selected:selected===id}} onPress={()=>setSelected(id)} style={[s.mission,selected===id&&s.selected]}><View style={{flexDirection:'row',justifyContent:'space-between',gap:8}}><Text style={s.name}>{String(l.number).padStart(2,'0')}  {l.title}</Text><Text style={s.stars}>{best?'★'.repeat(best.stars)+'☆'.repeat(3-best.stars):available?'OPEN':'LOCKED'}</Text></View><Text style={s.body}>{best?`Best ${best.seconds.toFixed(1)}s · ${best.completions} completed`:`${l.patrols.length} guard${l.patrols.length===1?'':'s'} · target ${Math.round(l.targetSeconds/60*10)/10} min`}</Text></Pressable></View>;})}
  <View style={s.briefing}><Text style={s.name}>{level.title}</Text><Text style={s.body}>{level.briefing}</Text><Text style={s.body}>Time limit: {level.hardLimitSeconds/60} min. Stars: escape; keep 40% charge; finish unseen within {level.targetSeconds}s.</Text></View>
  <Pressable disabled={!canPlay} accessibilityRole="button" accessibilityLabel={`Start ${level.title}`} onPress={()=>onStart(selected)} style={[s.start,!canPlay&&{opacity:.4}]}><Text style={s.startText}>{canPlay?'START HEIST ↗':'COMPLETE THE PREVIOUS MISSION'}</Text></Pressable>
  <Pressable accessibilityRole="button" onPress={onClose} style={{padding:12}}><Text style={[s.body,{textAlign:'center'}]}>Back to game</Text></Pressable>
 </ScrollView></View></Modal>;
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:'#081210ed',justifyContent:'center',padding:18},card:{flexGrow:0,maxHeight:'92%',borderRadius:24,borderWidth:1,borderColor:'#4a7062',backgroundColor:'#142421'},eyebrow:{color:'#a8ecd7',fontSize:10,letterSpacing:1.6,fontWeight:'700'},title:{fontSize:29,fontWeight:'800',color:'#e6eee3'},body:{fontSize:12,lineHeight:19,color:'#adc5b9'},mission:{gap:7,padding:14,borderRadius:12,borderWidth:1,borderColor:'#355046'},selected:{backgroundColor:'#29483e',borderColor:'#a8ecd7'},name:{fontSize:14,color:'#e5efe5',fontWeight:'700'},stars:{fontSize:11,color:'#badbba'},briefing:{padding:14,borderRadius:12,backgroundColor:'#0b1916',gap:9},start:{padding:16,borderRadius:12,backgroundColor:'#c8eadd'},startText:{fontSize:11,fontWeight:'800',textAlign:'center',color:'#143c2c'}});
