import {HapticPressable as Pressable} from '../feedback/HapticPressable';
import React,{type ReactNode} from 'react';
import {Image,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
export type MessageArt='success'|'caught'|'timeout'|'pause'|'recovery'|'pending';
// One identity, distinct expressions for every outcome. Generated from the courier reference.
export const messageArt:Record<MessageArt,ReturnType<typeof require>>={success:require('../../assets/messages/success.webp'),caught:require('../../assets/messages/caught.webp'),timeout:require('../../assets/messages/timeout.webp'),pause:require('../../assets/messages/pause.webp'),recovery:require('../../assets/messages/recovery.webp'),pending:require('../../assets/messages/pending.webp')};
type Action={label:string;accessibilityLabel?:string;onPress:()=>void;disabled?:boolean;spinner?:boolean};
export default function ResultSheet({art,eyebrow,title,detail,stats,stars,primary,secondary,utility,children,bottom=0,celebration=false,primarySide='right'}:{art:MessageArt;eyebrow:string;title:string;detail?:string;stats?:string;stars?:string;primary:Action;secondary?:Action;utility?:Action;children?:ReactNode;bottom?:number;celebration?:boolean;primarySide?:'left'|'right'}){
 const {width,height}=useWindowDimensions(),small=width<370||height<720;
 const button=(action:Action,main=false)=><Pressable accessibilityRole="button" accessibilityLabel={action.accessibilityLabel??action.label} disabled={action.disabled} spinner={action.spinner} onPress={()=>{action.onPress();}} style={[s.button,main?s.primary:s.secondary,action.disabled&&{opacity:.45}]}><Text style={[s.buttonText,{color:main?'#173337':'#CFE6E4'}]}>{action.label}</Text></Pressable>;
 return <View testID="result-backdrop" style={[s.backdrop,{paddingBottom:bottom}]}><View testID="result-sheet" accessibilityViewIsModal style={[s.sheet,celebration&&{borderColor:'#5C796A',backgroundColor:'#14211E'}]}>
 <View style={s.handle}/>{!celebration&&<View style={s.body}>{!celebration&&<Image testID={`message-art-${art}`} source={messageArt[art]} style={{width:small?88:120,height:small?96:126}} resizeMode="contain" accessible={false}/>}<View style={s.copy}><Text style={s.eyebrow}>{eyebrow}</Text><Text style={[s.title,small&&{fontSize:21}]}>{title}</Text>{!!stars&&<Text style={s.stars}>{stars}</Text>}{!!stats&&<Text style={s.stats}>{stats}</Text>}{!!detail&&<Text style={s.detail}>{detail}</Text>}</View></View>}
 {!!children&&<View style={[s.status,celebration&&{borderTopWidth:0,paddingTop:0,marginTop:0}]}>{children}</View>}<View style={s.actions}>{primarySide==='left'?<>{button(primary,true)}{!!secondary&&button(secondary)}</>:<>{!!secondary&&button(secondary)}{button(primary,true)}</>}</View>{!!utility&&<Pressable accessibilityRole="button" accessibilityLabel={utility.accessibilityLabel??utility.label} onPress={utility.onPress} style={s.utility}><Text style={s.utilityText}>{utility.label}</Text></Pressable>}
 </View></View>;
}
export function SubmissionStatus({state,message,children}:{state:'pending'|'saved'|'error';message:string;children?:ReactNode}){return <View style={{gap:4}}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><Image source={messageArt[state==='pending'?'pending':state==='error'?'recovery':'success']} style={{width:38,height:38}} resizeMode="contain"/><Text accessibilityLiveRegion="polite" numberOfLines={3} style={{flex:1,color:'#C2D5D0',fontSize:11,lineHeight:16}}>{message}</Text></View>{children}</View>;}
const s=StyleSheet.create({backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'#05080BA6',justifyContent:'flex-end',alignItems:'center',zIndex:30},sheet:{width:'100%',maxWidth:440,backgroundColor:'#16191D',borderWidth:1,borderColor:'#46515A',borderTopLeftRadius:24,borderTopRightRadius:24,paddingHorizontal:16,paddingTop:10,paddingBottom:16},handle:{alignSelf:'center',width:32,height:3,borderRadius:2,backgroundColor:'#4B585F',marginBottom:10},body:{flexDirection:'row',alignItems:'center',gap:12},copy:{flex:1,gap:7,paddingVertical:4},eyebrow:{fontSize:9,letterSpacing:1.5,fontWeight:'700',color:'#ACCBC6'},title:{fontSize:25,lineHeight:29,fontWeight:'800',color:'#F6F6F5',letterSpacing:-.6},stars:{color:'#CFE6E4',fontSize:19,letterSpacing:4},stats:{fontSize:12,lineHeight:18,color:'#DCEAE5',fontVariant:['tabular-nums']},detail:{fontSize:12,lineHeight:18,color:'#AEBDC1'},status:{borderTopWidth:1,borderColor:'#354047',paddingTop:8,marginTop:8},actions:{flexDirection:'row',gap:10,marginTop:12},button:{flex:1,minHeight:46,paddingVertical:11,paddingHorizontal:8,borderRadius:14,justifyContent:'center',alignItems:'center'},primary:{backgroundColor:'#CFE6E4'},secondary:{backgroundColor:'#202B30',borderWidth:1,borderColor:'#4A5B61'},buttonText:{fontSize:12,lineHeight:17,fontWeight:'800',textAlign:'center'},utility:{alignSelf:'center',minHeight:44,justifyContent:'center',paddingHorizontal:18,marginTop:4},utilityText:{color:'#B8C9CC',fontSize:11,fontWeight:'600'}});
