import fs from 'node:fs/promises';
import path from 'node:path';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont,finalizePresentation} from '/Users/bluntbrain/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root=process.cwd(),tmp=path.join(root,'.submission-build'),skill='/Users/bluntbrain/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations',font=resolvePresentationFont();
const deck=Presentation.create({slideSize:{width:1280,height:720}});
function text(s,str,x,y,w,h,size=30,color='#D6E9E1',bold=false){const t=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});t.text=str;t.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return t;}
async function img(s,file,x,y,w,h){s.images.add({blob:new Uint8Array(await fs.readFile(path.join(root,file))),contentType:'image/png',alt:file,fit:'contain',position:{left:x,top:y,width:w,height:h}});}
function slide(title){const s=deck.slides.add();s.background.fill='#0C0C0E';text(s,title,72,62,1100,94,52,'#F1F5EE',true);return s;}
let s=slide('Steal a Seeker');text(s,'A solo stealth game for Solana Mobile',72,200,580,130,36);text(s,'Recover the phone.\nSurvive the escape.',72,355,580,160,42,'#CFE6E4',true);text(s,'CLOCK IN 2026 · Development review',72,635,670,40,22);await img(s,'assets/paywall-v3/courier-heist.png',720,120,500,520);s.speakerNotes.textFrame.setText('Original project artwork. Current development review, not an official Solana endorsement. Source: repository game and UI.');
s=slide('The theft changes the run');text(s,'Before pickup, watch patrols and use cover.\n\nAfter pickup, guards accelerate and receive periodic position reports.\n\nA decoy buys time. A dash spends phone charge.',72,200,720,390,30);await img(s,'verification/release-coach.png',910,160,270,530);s.speakerNotes.textFrame.setText('Browser gameplay screenshot. Rules: src/game/level.ts and src/game/guards.ts. Guard speed ramps from 2.2x to 2.8x over 20 seconds after alarm. Position reports every four seconds. This is not physical Android evidence.');
s=slide('Twelve missions across three districts');text(s,'Warehouse',72,184,320,55,32,'#CFE6E4',true);text(s,'Learn patrols, cover and battery limits.',72,505,320,120,28);await img(s,'assets/world-v3/district-warehouse.png',55,255,350,220);text(s,'Rooftops',470,184,320,55,32,'#CFE6E4',true);text(s,'Cross exposed lanes and time moving gates.',470,505,320,120,28);await img(s,'assets/world-v3/district-rooftops.png',450,255,350,220);text(s,'Powerworks / Vault',870,184,350,55,30,'#CFE6E4',true);text(s,'Switch circuits, open relays and recover multiple targets.',870,505,330,145,28);await img(s,'assets/world-v3/district-powerworks.png',850,255,350,220);s.speakerNotes.textFrame.setText('District images are authored game assets, not gameplay screenshots. Source: src/game/level.ts; four campaign missions per district.');
s=slide('A reason to try another run');text(s,'Recover a different virtual phone in each mission.\n\nFinish the collection, then improve your stars or attempt the daily route.\n\nThe daily route resets at 00:00 UTC. Everyone uses the same loadout.',72,190,725,370,30);await img(s,'verification/release-daily.png',910,158,270,525);text(s,'Habit and retention are hypotheses to test with outside players.',72,618,770,66,23,'#A7BCC1');s.speakerNotes.textFrame.setText('Screenshot: local browser daily practice. Live ranks are separate. Ranking uses one best server-replayed complete run per wallet, score descending then ticks ascending; exact ties share rank. Sources: shared/daily.ts, server/ranked-service.ts. No real-player retention data claimed.');
s=slide('Solana integration');text(s,'Mobile Wallet Adapter opens wallet approval on Android.\n\nThe backend checks devnet transfers before granting campaign access and owned outfits.\n\nIt replays submitted inputs before accepting a ranked score.',72,180,750,380,31);await img(s,'assets/messages/recovery.png',880,200,320,340);text(s,'TEST SKR has no monetary value. Physical Phantom payment testing is pending.',72,605,1120,70,25,'#A7BCC1');s.speakerNotes.textFrame.setText('Sources: src/wallet, src/commerce, server/service.ts, server/ranked-service.ts. Normal native app has a hard paywall. Judge APK grants only offline campaign access; it cannot authorize online purchases or results. No live mainnet or completed physical wallet round trip is claimed.');
s=slide('Review build and remaining proof');text(s,'83 client / gameplay tests pass\n52 backend tests pass\n12 deterministic simulation routes pass',72,184,1040,165,35,'#CFE6E4',true);text(s,'Signed arm64 Android builds and source are included.\n\nNext gates: outside-player feedback, a complete device playthrough, a physical devnet wallet round trip and the final three-minute demo.',72,398,1110,205,30);text(s,'Private source: github.com/bluntbrain/steal-a-seeker-clockin',72,643,1120,38,22,'#A7BCC1');s.speakerNotes.textFrame.setText('Evidence: tests/*.test.ts, server/*.test.ts, verification and release manifests. Test counts from September 13, 2026 run. Automated current browser pointer route cleared missions 1–3 but failed mission 4 timing phases; no all-12 browser or real-player completion claim. Owner must grant confirmed judges access to the private repository.');
await(await PresentationFile.exportPptx(deck)).save(path.join(tmp,'candidate-v3.pptx'));
for(let i=0;i<deck.slides.items.length;i++){const slide=deck.slides.items[i];const png=await deck.export({slide,format:'png',scale:1});await fs.writeFile(path.join(tmp,`slide-${i+1}.png`),new Uint8Array(await png.arrayBuffer()));}
await finalizePresentation({workspaceDir:root,candidatePath:path.join(tmp,'candidate-v3.pptx'),finalPath:path.join(root,'submission/steal-a-seeker-pitch.pptx'),pythonExecutable:'/Users/bluntbrain/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],requiredNativeTableOwnerSlides:[],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:path.join(tmp,'validation-v3.json')});console.log('Deck written with font '+font);
