import React,{useState} from 'react';
const {createRoot}=require('react-dom/client') as {createRoot:(element:HTMLElement)=>{render:(node:React.ReactNode)=>void}};
import CourierCard,{CourierCardSurface} from '../src/league/CourierCard';
import {shareCard} from '../src/league/shareCard.web';
import type {CourierCardData} from '../src/league/card';
const base:CourierCardData={week:'2026-09-14',rank:34,participants:58,points:18820,cleared:2,ticks:4035,domain:'courier.skr',wallet:'SampleWalletForDesignReview123456789',local:false,final:false,earned:false};
const examples:Record<string,CourierCardData>={live:base,final:{...base,rank:3,points:28180,cleared:3,ticks:6120,final:true,earned:true},local:{...base,local:true},unranked:{...base,rank:null,points:0,cleared:0,ticks:0},long:{...base,domain:'this-is-a-long-courier-name-used-only-for-layout-review.skr'},wallet:{...base,domain:null}};
function Gallery(){const [which,setWhich]=useState('live'),[native,setNative]=useState(false),[ready,setReady]=useState(false),[message,setMessage]=useState('');const data=examples[which]!,Component=native?CourierCardSurface:CourierCard;
 return <main><header><small>STEAL A SEEKER · COURIER CARD V2</small><h1>Your weekly result. Worth keeping.</h1><p>GPT Image 2.5 Flare artwork, with real text rendered by the app. All data shown on this review page is sample data.</p><a href="/?build=courier-card-v2">Open the game</a></header><div className="layout"><section><div className="controls"><label>Card state <select value={which} onChange={e=>setWhich(e.target.value)}>{Object.keys(examples).map(k=><option key={k} value={k}>{k}</option>)}</select></label><label>Preview renderer <select value={native?'native':'web'} onChange={e=>{setReady(false);setNative(e.target.value==='native')}}><option value="web">Web / shared SVG</option><option value="native">Native component on web</option></select></label></div><div className="card"><Component data={data} width={Math.min(window.innerWidth-48,440)} onReady={setReady}/></div><button disabled={!ready} onClick={()=>void shareCard(data,null,true).then(()=>setMessage('PNG download created.')).catch(e=>setMessage(String(e)))}>Download sample PNG</button><p role="status">{message}</p></section><aside><h2>Data stays accurate</h2><p>Name or wallet, rank and total ranked couriers, total points, missions cleared, counted-run time and the UTC week.</p><p>Live cards say the rank can change. Final cards use the archived result. Browser cards clearly say TEST. Ghost Courier appears only after all three missions are cleared.</p><h2>Ready to share</h2><p>The PNG is 1080 × 1620. Artwork is embedded so it survives exports. Android sharing waits until the artwork loads. The name editor stays folded until you need it.</p><p>No token payout is claimed. The old Devnet text and “contracts” wording are gone.</p><a href="sample-live.png">Open full sample image</a></aside></div></main>;
}
createRoot(document.getElementById('root')!).render(<Gallery/>);
