/** Run capture before an operator restart, then verify after health recovers. Read-only API except auth. */
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,chmodSync} from 'node:fs';
import {homedir} from 'node:os';
import {join} from 'node:path';
import {createPrivateKey,sign} from 'node:crypto';
import {getBase58Decoder} from '@solana/kit';
import {createSignInMessage} from '@solana/wallet-standard-util';
const base=process.env.QA_API_URL?.replace(/\/$/,'');if(!base?.startsWith('https://'))throw new Error('HTTPS QA_API_URL required.');
const root=join(homedir(),'.config/steal-a-seeker/qa'),checkpointPath=join(root,'restart-checkpoint.json');
const key=Uint8Array.from(JSON.parse(readFileSync(join(root,'buyer.json'),'utf8'))),wallet=getBase58Decoder().decode(key.slice(32)),privateKey=createPrivateKey({key:Buffer.concat([Buffer.from('302e020100300506032b657004220420','hex'),Buffer.from(key.slice(0,32))]),format:'der',type:'pkcs8'});
async function call(path:string,token?:string,body?:unknown){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{...(body?{'content-type':'application/json'}:{}),...(token?{authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});assert.equal(r.status,200,`${path} status ${r.status}`);return r.json() as Promise<any>;}
async function login(){const c=await call('/auth/challenge',undefined,{wallet}),message=createSignInMessage(c.payload),a=await call('/auth/verify',undefined,{id:c.id,wallet,signedMessage:Buffer.from(message).toString('base64'),signature:sign(null,message,privateKey).toString('base64')});return a.token as string;}
async function snapshot(token:string){const me=await call('/me',token),campaign=await call('/campaign',token),orders=await call('/orders',token),daily=await call('/daily'),board=await call(`/daily/${daily.day}/leaderboard`,token);assert.deepEqual([...me.entitlements].sort(),['campaign','night-courier']);assert.equal(me.equipment.outfit,'night-courier');assert.equal(campaign.runs.length,12);assert.equal(campaign.state,'settled');assert.equal(orders.filter((o:any)=>o.status==='fulfilled').length,2);assert.equal(board.personal.wallet,wallet);return {me,campaign:{...campaign,runs:[...campaign.runs].sort((a,b)=>a.mission.localeCompare(b.mission))},orders:orders.map((o:any)=>({id:o.id,sku:o.sku,status:o.status,signature:o.signature})).sort((a:any,b:any)=>a.sku.localeCompare(b.sku)),day:daily.day,personal:board.personal};}
async function main(){if(process.argv[2]==='capture'){const token=await login(),state=await snapshot(token);writeFileSync(checkpointPath,JSON.stringify({base,token,state,capturedAt:new Date().toISOString()}),{mode:0o600});chmodSync(checkpointPath,0o600);console.log('Private pre-restart checkpoint captured; no session printed.');return;}
 const before=JSON.parse(readFileSync(checkpointPath,'utf8'));assert.equal(before.base,base);await call('/health');const existingSession=await snapshot(before.token);assert.deepEqual(existingSession,before.state,'Existing session and application state survive restart');const token=await login();assert.deepEqual(await snapshot(token),before.state,'Fresh signed login restores the same state');const report={checkedAt:new Date().toISOString(),base,wallet,passed:3,failed:0,checks:['Pre-restart session remains valid','Campaign, 12 verified wins, cosmetics, progress and settled payout persist','New wallet login restores identical receipts and daily personal leaderboard'],beforeCapturedAt:before.capturedAt,limitations:['Operator confirms a new deployment actually restarted the service.']};writeFileSync('verification/deployed-api-qa-restore.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));}
main().catch(e=>{console.error(e instanceof Error?e.message:'Restore verification failed');process.exitCode=1;});
