/** Safe live HTTP QA: disposable wallets, normal app APIs, devnet only. Never touches a DB directly.
 * QA_API_URL=https://... npx tsx scripts/qa-deployed-api.ts
 * Add QA_COMMERCE=1 after funding ~/.config/steal-a-seeker/qa/buyer.json with devnet SOL and 120 TEST SKR.
 * Results contain public identifiers and pass/fail only; no keys, tokens, signed login messages or raw bodies.
 */
import assert from 'node:assert/strict';
import {createPrivateKey,sign,randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {homedir} from 'node:os';
import {join} from 'node:path';
import {getBase58Decoder,createKeyPairFromBytes,signTransaction,getBase64EncodedWireTransaction} from '@solana/kit';
import {createSignInMessage} from '@solana/wallet-standard-util';
import {paymentTransaction} from '../src/commerce/payment';
import {fixtureReplay} from '../tests/fixtures/replay';
import {CAMPAIGN_IDS} from '../src/game/level';
import rules from '../shared/rules-manifest.json';
import {DEVNET_GENESIS} from '../server/chain';
const base=process.env.QA_API_URL?.replace(/\/$/,'');
if(!base || !base.startsWith('https://'))throw new Error('QA_API_URL must be an HTTPS deployment.');
const rpcUrl=process.env.QA_RPC_URL||'https://api.devnet.solana.com',commerce=process.env.QA_COMMERCE==='1';
const results:{name:string;status:string;milliseconds:number;detail?:string}[]=[];
const report:any={startedAt:new Date().toISOString(),base,mode:commerce?'real-devnet-commerce':'HTTP-access-and-fail-closed',results,limitations:[],publicTransactions:[]};
const reportPath=join(process.cwd(),'verification/deployed-api-qa.json');mkdirSync(join(process.cwd(),'verification'),{recursive:true});
function save(){report.finishedAt=new Date().toISOString();report.passed=results.filter(x=>x.status==='pass').length;report.failed=results.filter(x=>x.status==='fail').length;writeFileSync(reportPath,JSON.stringify(report,null,2)+'\n');}
async function test(name:string,fn:()=>Promise<void>){const t=Date.now();try{await fn();results.push({name,status:'pass',milliseconds:Date.now()-t});console.log(`PASS ${name}`);}catch(e){results.push({name,status:'fail',milliseconds:Date.now()-t,detail:e instanceof Error?e.message.slice(0,400):'Failure'});console.log(`FAIL ${name}`);}save();}
async function api(method:string,path:string,body?:unknown,token?:string){const response=await fetch(base+path,{method,headers:{...(body!==undefined?{'content-type':'application/json'}:{}),...(token?{authorization:`Bearer ${token}`}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});let data:any;try{data=await response.json();}catch{data=null;}return {status:response.status,data};}
async function call(method:string,path:string,status:number,body?:unknown,token?:string){const r=await api(method,path,body,token);assert.equal(r.status,status,`${method} ${path}: expected ${status}, got ${r.status}${r.data?.error?` (${r.data.error})`:''}`);return r.data;}
async function rpc(method:string,params:unknown[]=[]){const response=await fetch(rpcUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:AbortSignal.timeout(30000)});const body:any=await response.json();if(body.error)throw new Error(`Devnet RPC ${method} failed (${body.error.code})`);return body.result;}
function wallet(name:string){const bytes=Uint8Array.from(JSON.parse(readFileSync(join(homedir(),'.config/steal-a-seeker/qa',`${name}.json`),'utf8')));return {bytes,address:getBase58Decoder().decode(bytes.slice(32)),privateKey:createPrivateKey({key:Buffer.concat([Buffer.from('302e020100300506032b657004220420','hex'),Buffer.from(bytes.slice(0,32))]),format:'der',type:'pkcs8'}),token:''};}
const buyer=wallet('buyer'),other=wallet('other');report.wallets={buyer:buyer.address,other:other.address};
async function login(w:ReturnType<typeof wallet>){const challenge=await call('POST','/auth/challenge',200,{wallet:w.address});assert.equal(challenge.payload.chainId,'solana:devnet');const message=createSignInMessage(challenge.payload);const payload={id:challenge.id,wallet:w.address,signedMessage:Buffer.from(message).toString('base64'),signature:sign(null,message,w.privateKey).toString('base64')};const auth=await call('POST','/auth/verify',200,payload);assert.equal(auth.account.wallet,w.address);w.token=auth.token;return payload;}
const progress={version:1,missions:{practice:{stars:2,seconds:25,score:11500,battery:60,completions:2}}};
let daily:any;
async function main(){
 await test('HTTPS health: database reachable, devnet cluster',async()=>{const r=await call('GET','/health',200);assert.equal(r.ok,true);assert.equal(r.cluster,'solana:devnet');});
 await test('Catalog: six products, $10 campaign, SKR/SOL and cosmetic-only outfits',async()=>{const c=await call('GET','/catalog',200);assert.equal(c.cluster,'solana:devnet');assert.deepEqual(c.paymentCurrencies,['SKR','SOL']);assert.equal(c.products.length,6);assert.equal(c.products.find((p:any)=>p.id==='campaign').usdCents,1000);assert(c.products.filter((p:any)=>p.kind==='outfit').every((p:any)=>p.description.includes('Same gameplay stats')));});
 await test('Private routes require a signed session',async()=>{for(const path of ['/me','/orders','/campaign','/runs/current','/paid/entries'])await call('GET',path,401);await call('GET','/me',401,undefined,'not-a-token');});
 await test('Bad wallet and unknown fields are rejected',async()=>{await call('POST','/auth/challenge',400,{wallet:'bad'});await call('POST','/auth/challenge',400,{wallet:buyer.address,admin:true});});
 await test('Real Ed25519 wallet authentication and nonce replay rejection',async()=>{const payload=await login(buyer);await call('POST','/auth/verify',401,payload);await login(other);});
 await test('Another wallet cannot use buyer signature or changed message',async()=>{const c=await call('POST','/auth/challenge',200,{wallet:other.address}),message=createSignInMessage(c.payload);await call('POST','/auth/verify',401,{id:c.id,wallet:other.address,signedMessage:Buffer.from(message).toString('base64'),signature:sign(null,message,buyer.privateKey).toString('base64')});});
 await test('Authenticated accounts stay wallet-isolated',async()=>{assert.equal((await call('GET','/me',200,undefined,buyer.token)).wallet,buyer.address);const o=await call('GET','/me',200,undefined,other.token);assert.equal(o.wallet,other.address);assert.deepEqual(o.entitlements,[]);});
 await test('Daily manifest: current UTC date and pinned current rules',async()=>{daily=await call('GET','/daily',200);assert.equal(daily.day,new Date().toISOString().slice(0,10));assert.equal(daily.rulesHash,rules.rulesHash);assert.equal(daily.loadout,'standard');assert(CAMPAIGN_IDS.includes(daily.mission));assert.deepEqual(await call('GET','/daily',200),daily);});
 await test('Public leaderboards and invalid dates',async()=>{const b=await call('GET',`/daily/${daily.day}/leaderboard`,200);assert(Array.isArray(b.entries));assert.equal(b.personal,null);assert(Array.isArray(await call('GET','/campaign/leaderboard',200)));await call('GET','/daily/2026-99-99/leaderboard',400);await call('GET','/daily/1900-01-01/leaderboard',404);});
 await test('Locked campaign, ranked entry, progress and cosmetics cannot be bypassed',async()=>{await call('POST','/runs',403,{day:daily.day,rulesHash:daily.rulesHash,requestKey:randomUUID()},other.token);await call('PUT','/me/progress',403,progress,other.token);await call('PUT','/me/equipment',403,{sku:'night-courier'},other.token);await call('POST','/campaign/claim',403,{},other.token);await call('POST','/campaign/runs',403,{mission:'practice',rulesHash:daily.rulesHash,replay:{version:1,chunks:[{x:0,y:0,buttons:0,ticks:1}]}},other.token);});
 await test('Legacy paid-per-run feature stays disabled',async()=>{assert.equal((await call('GET','/paid/challenge',200)).enabled,false);await call('POST','/paid/entries',503,{requestKey:randomUUID(),termsVersion:'devnet-v1'},other.token);});
 await test('Server price and schema cannot be overridden',async()=>{await call('POST','/orders',400,{sku:'campaign',idempotencyKey:randomUUID(),amount:'1'},buyer.token);await call('POST','/orders',400,{sku:'nonexistent',idempotencyKey:randomUUID()},buyer.token);await call('PUT','/me/progress',400,{...progress,wallet:buyer.address},other.token);});
 await test('Unknown wallet-owned resources do not leak data',async()=>{for(const path of ['/orders/','/runs/','/returns/'])await call('GET',path+randomUUID(),404,undefined,other.token);});
 if(commerce)await fullCommerce();else{
  await test('Unfunded checkout fails closed or reports ready without taking payment',async()=>{const q=await api('POST','/orders',{sku:'campaign',idempotencyKey:randomUUID()},buyer.token);assert([200,503].includes(q.status));report.checkoutState=q.status===200?'Quote ready; paid flow not requested':'Payments fail closed before approval';if(q.status===200){assert.ok(q.data.pricing.usdCents>=1000);assert.equal(q.data.cluster,'solana:devnet');}});
  report.limitations.push('Real token transfer, paid unlock, successful verified replay, completion payout and restart persistence require the funded commerce pass.');
 }
 await test('Logout revokes the session',async()=>{await call('POST','/auth/logout',200,{},other.token);await call('GET','/me',401,undefined,other.token);});
 save();console.log(JSON.stringify({passed:report.passed,failed:report.failed,report:reportPath}));if(report.failed)process.exitCode=1;
}
async function fullCommerce(){
 await test('RPC is devnet; dedicated QA buyer has transaction fees',async()=>{assert.equal(await rpc('getGenesisHash'),DEVNET_GENESIS);assert((await rpc('getBalance',[buyer.address])).value>=1000000);});
 let order:any,key=randomUUID();
 await test('Campaign quote, idempotency and cross-wallet access',async()=>{order=await call('POST','/orders',200,{sku:'campaign',idempotencyKey:key},buyer.token);assert.ok(order.pricing!.usdCents>=1000);assert.equal(order.cluster,'solana:devnet');assert.equal(order.campaignTerms.rebate,25);assert.equal((await call('POST','/orders',200,{sku:'campaign',idempotencyKey:key},buyer.token)).id,order.id);await call('POST','/orders',409,{sku:'night-courier',idempotencyKey:key},buyer.token);await call('GET',`/orders/${order.id}`,404,undefined,other.token);await call('POST',`/orders/${order.id}/prepare`,404,{},other.token);});
 await test('Campaign approval reserves rebate and reuses payment lifetime',async()=>{order=await call('POST',`/orders/${order.id}/prepare`,200,{},buyer.token);assert(order.payment);assert.deepEqual((await call('POST',`/orders/${order.id}/prepare`,200,{},buyer.token)).payment,order.payment);});
 await test('Real devnet campaign transfer and duplicate callback grant one entitlement',async()=>{await purchase(order,true);const me=await call('GET','/me',200,undefined,buyer.token);assert.equal(me.entitlements.filter((x:string)=>x==='campaign').length,1);await call('POST','/orders',409,{sku:'campaign',idempotencyKey:randomUUID()},buyer.token);assert.deepEqual((await call('GET','/me',200,undefined,other.token)).entitlements,[]);});
 await test('Owned campaign sync restores and preserves best progress',async()=>{await call('PUT','/me/progress',200,progress,buyer.token);await call('PUT','/me/progress',200,{version:1,missions:{practice:{stars:1,seconds:30,score:10000,battery:40,completions:1}}},buyer.token);assert.deepEqual((await call('GET','/me',200,undefined,buyer.token)).progress,progress);await login(buyer);assert((await call('GET','/me',200,undefined,buyer.token)).entitlements.includes('campaign'));});
 await test('Real outfit payment without callback restores by reference and equips',async()=>{const o=await call('POST','/orders',200,{sku:'night-courier',idempotencyKey:randomUUID()},buyer.token),prepared=await call('POST',`/orders/${o.id}/prepare`,200,{},buyer.token);assert.equal(prepared.amount,'20000000');await purchase(prepared,false);assert.equal((await call('PUT','/me/equipment',200,{sku:'night-courier'},buyer.token)).equipment.outfit,'night-courier');});
 await test('Rebate cannot be claimed before all twelve verified levels',async()=>{await call('POST','/campaign/claim',409,{},buyer.token);});
 await test('Ranked ticket idempotency, stale rules, isolation and abandonment',async()=>{await call('POST','/runs',409,{day:daily.day,rulesHash:'a'.repeat(64),requestKey:randomUUID()},buyer.token);const body={day:daily.day,rulesHash:daily.rulesHash,requestKey:randomUUID()},run=await call('POST','/runs',200,body,buyer.token);assert.equal((await call('POST','/runs',200,body,buyer.token)).id,run.id);await call('GET',`/runs/${run.id}`,404,undefined,other.token);await call('POST','/runs',409,{...body,requestKey:randomUUID()},buyer.token);assert.equal((await call('POST',`/runs/${run.id}/abandon`,200,{},buyer.token)).status,'abandoned');});
 await test('Ranked worker rejects unfinished replay without leaderboard credit',async()=>{const run=await call('POST','/runs',200,{day:daily.day,rulesHash:daily.rulesHash,requestKey:randomUUID()},buyer.token);await call('POST',`/runs/${run.id}/finish`,200,{rulesHash:daily.rulesHash,replay:{version:1,chunks:[{x:0,y:0,buttons:0,ticks:1}]}},buyer.token);const result=await poll(`/runs/${run.id}`,r=>r.status!=='verifying');assert.equal(result.status,'rejected');});
 await test('Successful daily replay verifies server score and reaches personal leaderboard',async()=>{const f=fixtureReplay(daily.mission);assert.equal(f.state.status,'won');const run=await call('POST','/runs',200,{day:daily.day,rulesHash:daily.rulesHash,requestKey:randomUUID()},buyer.token),body={rulesHash:daily.rulesHash,replay:f.replay};await call('POST',`/runs/${run.id}/finish`,400,{...body,score:999999},buyer.token);await call('POST',`/runs/${run.id}/finish`,400,body,buyer.token);const elapsed=Date.now()-new Date(run.issuedAt).getTime();await new Promise(r=>setTimeout(r,Math.max(0,f.state.ticks/30*1000-elapsed+500)));await call('POST',`/runs/${run.id}/finish`,200,body,buyer.token);const result=await poll(`/runs/${run.id}`,r=>r.status!=='verifying');assert.equal(result.status,'verified');assert.equal(result.result.score,f.state.score);assert.equal(result.result.ticks,f.state.ticks);const board=await call('GET',`/daily/${daily.day}/leaderboard`,200,undefined,buyer.token);assert.equal(board.personal.wallet,buyer.address);assert.equal(board.personal.score,f.state.score);assert.equal(board.entries.filter((r:any)=>r.wallet===buyer.address).length,1);assert.equal((await call('POST',`/runs/${run.id}/finish`,200,body,buyer.token)).status,'verified');});
 await test('All twelve actual replay fixtures verify once per level; repeat is idempotent',async()=>{for(const mission of CAMPAIGN_IDS){const f=fixtureReplay(mission);assert.equal(f.state.status,'won',`Local route ${mission}`);const body={mission,rulesHash:rules.rulesHash,replay:f.replay};const first=await call('POST','/campaign/runs',200,body,buyer.token);assert(first.runs.some((r:any)=>r.mission===mission));await new Promise(r=>setTimeout(r,5100));}const f=fixtureReplay('practice');const summary=await call('POST','/campaign/runs',200,{mission:'practice',rulesHash:rules.rulesHash,replay:f.replay},buyer.token);assert.equal(summary.runs.length,12);assert.equal(summary.state,'ready');});
 await test('Completion rebate settles 25 TEST SKR once and returns stay wallet-isolated',async()=>{const before=await rpc('getTokenAccountBalance',[order.source]);const claim=await call('POST','/campaign/claim',200,{},buyer.token);assert(claim.returnId);await call('GET',`/returns/${claim.returnId}`,404,undefined,other.token);const settled=await poll(`/returns/${claim.returnId}`,r=>r.state==='settled',180000);report.publicTransactions.push({kind:'completion-rebate',signature:settled.receipt?.signature||settled.signature});const after=await rpc('getTokenAccountBalance',[order.source]);assert.equal(BigInt(after.value.amount)-BigInt(before.value.amount),25000000n);assert.equal((await call('POST','/campaign/claim',200,{},buyer.token)).returnId,claim.returnId);});
 report.limitations.push('Automated signed-wallet and deterministic replay QA; not a physical-device Phantom approval or human playtest. Service restart recovery must be separately checked by operator.');
}
async function poll(path:string,done:(r:any)=>boolean,timeout=90000){const until=Date.now()+timeout;while(Date.now()<until){const r=await call('GET',path,200,undefined,buyer.token);if(done(r))return r;await new Promise(r=>setTimeout(r,2500));}throw new Error(`Timed out waiting for ${path}`);}
async function purchase(order:any,callback:boolean){assert.equal(order.cluster,'solana:devnet');assert.equal(await rpc('getGenesisHash'),DEVNET_GENESIS);const kp=await createKeyPairFromBytes(buyer.bytes),signed=await signTransaction([kp],paymentTransaction(order));const wire=getBase64EncodedWireTransaction(signed),signature=await rpc('sendTransaction',[wire,{encoding:'base64',skipPreflight:false,preflightCommitment:'finalized',maxRetries:3}]);report.publicTransactions.push({kind:order.sku,signature});if(callback)await call('POST',`/orders/${order.id}/transaction`,200,{signature},buyer.token);const until=Date.now()+120000;let final:any;while(Date.now()<until){final=await call('POST',`/orders/${order.id}/reconcile`,200,{},buyer.token);if(final.status==='fulfilled')break;await new Promise(r=>setTimeout(r,3000));}assert.equal(final?.status,'fulfilled');if(callback)assert.equal((await call('POST',`/orders/${order.id}/transaction`,200,{signature},buyer.token)).status,'fulfilled');}
main().catch(e=>{report.fatal=e instanceof Error?e.message.slice(0,400):'Fatal error';save();console.error('QA failed before completion; see sanitized report.');process.exitCode=1;});
