// Dedicated devnet QA identity; no token transfer and no verified score is submitted.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {homedir} from 'node:os';
import {join} from 'node:path';
import {createPrivateKey,sign,randomUUID} from 'node:crypto';
import {getBase58Decoder} from '@solana/kit';
import {createSignInMessage} from '@solana/wallet-standard-util';
const base='https://seeker-api-production-41b3.up.railway.app';
async function api(path:string,token?:string,body?:unknown){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});assert.equal(r.status,200,path);return r.json() as Promise<any>;}
async function main(){assert.equal((await api('/health')).cluster,'solana:devnet');const bytes=Uint8Array.from(JSON.parse(readFileSync(join(homedir(),'.config/steal-a-seeker/qa/usd-sol-buyer.json'),'utf8'))),wallet=getBase58Decoder().decode(bytes.slice(32)),key=createPrivateKey({key:Buffer.concat([Buffer.from('302e020100300506032b657004220420','hex'),Buffer.from(bytes.slice(0,32))]),format:'der',type:'pkcs8'}),c=await api('/auth/challenge',undefined,{wallet}),message=createSignInMessage(c.payload),auth=await api('/auth/verify',undefined,{id:c.id,wallet,signedMessage:Buffer.from(message).toString('base64'),signature:sign(null,message,key).toString('base64')});
 try{const before=await api('/league',auth.token);assert.equal(before.contracts.length,3);assert.equal(before.authenticated,true);assert.equal(before.active,null);const contract=before.contracts.find((c:any)=>(before.attempts[c.id]??0)<5);assert(contract);const request={contractId:contract.id,rulesHash:before.rulesHash,requestKey:randomUUID()},one=await api('/league/start',auth.token,request),two=await api('/league/start',auth.token,request);assert.equal(one.id,two.id);assert.deepEqual(one.manifest.contract,contract);await api(`/runs/${one.id}/abandon`,auth.token,{});const after=await api('/league',auth.token);assert.equal(after.attempts[contract.id],(before.attempts[contract.id]??0)+1);assert.equal(after.board.personal,null);assert.equal(after.active,null);writeFileSync('verification/contracts/live-api.json',JSON.stringify({week:after.week,contracts:after.contracts.map((c:any)=>({id:c.id,name:c.name,modifier:c.modifier})),checks:['devnet health','wallet authentication','three immutable contracts','idempotent ranked start','one attempt consumed','abandonment','no score from abandoned attempt'],noTokenTransfers:true},null,2));console.log('PASS live league: sign-in, three contracts, duplicate request, one attempt, abandonment, no score');}finally{await api('/auth/logout',auth.token,{});}}
main().catch(e=>{console.error(e instanceof Error?e.message:'QA failed');process.exitCode=1;});
